Refactor #10078 v98 XCUITests update FullFunctional Test suite
mozilla-mobile/firefox-ios pull request #10091
Opened 2022-02-24 18:30 UTC by isabelrios

Fixes #10078

2022-02-24 18:36 UTC, isabelrios commented on bitrise.yml
> +        - simulator_device: iPhone 11
TODO: Change back to previous value

2022-03-03 08:35 UTC, isabelrios commented
@AaronMT @SimonBasca could I please get your review on this? we would need the test fixes for L10n screenshots as a new round is required soon. Thank you 🙏

2022-03-03 08:37 UTC, SimonBasca commented on L10nSnapshotTests/L10nSuite2SnapshotTests.swift
> +        print(app.debugDescription)
Nit: Remove debugDescription.

2022-03-03 08:45 UTC, SimonBasca commented on XCUITests/ReaderViewUITest.swift
> +//        navigator.goto(LibraryPanel_ReadingList)
Nit: I think this can be removed.

2022-03-03 08:47 UTC, SimonBasca commented on XCUITests/SearchTest.swift
> +//        print(app.debugDescription)
Remove comments and "debugDescription"

2022-03-03 08:48 UTC, SimonBasca commented on XCUITests/ReaderViewUITest.swift
> +//        userState.url = path(forTestPage: "test-mozilla-book.html")
Remove comments.

2022-03-03 08:48 UTC, SimonBasca commented on XCUITests/ReaderViewUITest.swift
> +//        navigator.goto(BrowserTab)
Remove comments.

2022-03-03 08:48 UTC, SimonBasca commented on XCUITests/ReaderViewUITest.swift
> +//        navigator.browserPerformAction(.addReadingListOption)
Remove comments.

2022-03-03 08:51 UTC, SimonBasca requested changes
Looks good, just a few comments need addressing.

2022-03-03 09:35 UTC, SimonBasca commented on XCUITests/ReaderViewUITest.swift
> +        print(app.debugDescription)
Nit: Remove `print(app.debugDescription)`

2022-03-03 09:53 UTC, SimonBasca approved these changes

2022-03-03 10:18 UTC, merged