Refactor FXIOS-2040 [v104] Removed SnapKit from TabLocationView, TabToolbar, and TabToolbarHelper
mozilla-mobile/firefox-ios pull request #11229
Opened 2022-07-08 02:33 UTC by KrisRJack

Related to https://github.com/mozilla-mobile/firefox-ios/issues/8592

This PR includes replacement for SnapKit in TabLocationView, TabToolbar, and TabToolbarHelper. 

Additionally, this PR includes two helper functions in UIView extensions:
- `edges(equalTo: UIView, constant: CGFloat)` - Makes the edge constraints of a view equaled to the edge constrains of another view.
-  `center(equalTo: UIView)` - Makes x and y anchors of a view equaled to that of another view.

2022-07-08 02:35 UTC, KrisRJack commented on Client/Frontend/Toolbar+URLBar/TabLocationView.swift
> +        contentView.edges(equalTo: self)
This function was created [here](https://github.com/mozilla-mobile/firefox-ios/blob/fc4eb7dee8077f11a36ee76f180913af0b65c5ab/Client/Extensions/UIViewExtensions.swift#L74)

2022-07-08 13:40 UTC, electricRGB commented on Client/Extensions/UIViewExtensions.swift
> +     */
Same comment as above re docs. :)

2022-07-08 13:45 UTC, electricRGB commented on Client/Frontend/Toolbar+URLBar/TabLocationView.swift
> +            trackingProtectionButton.heightAnchor.constraint(equalToConstant: TabLocationViewUX.ButtonSize),
```suggestion
            trackingProtectionButton.heightAnchor.constraint(equalToConstant: TabLocationViewUX.ButtonSize),

```
nit: vertical space is cheap and it helps improve legibility by separating constraints for different objects.

2022-07-08 13:48 UTC, electricRGB requested changes
Heya. Thanks for your continuing contributions! Just a few comments to slightly improve some of the good stuff here, before I get to running this locally & on BR so we can eventually merge.

2022-07-09 00:49 UTC, KrisRJack commented on Client/Extensions/UIViewExtensions.swift
> +     */
Neat! Will use `Option + Command + /` more often. Did not know that shortcut existed 😅

2022-07-11 14:36 UTC, electricRGB approved these changes

2022-07-11 14:39 UTC, electricRGB commented
BR is being silly. Closing & reopening to re-run.

2022-07-11 18:30 UTC, electricRGB commented
BR is green

![Screen Shot 2022-07-11 at 2 20 26 PM](https://user-images.githubusercontent.com/11182210/178333277-337d38ef-de27-41bb-83f6-0e61b9c30c16.png)

2022-07-13 10:17 UTC, KrisRJack commented
@electricRGB Done! Thanks for your review!

2022-07-14 14:42 UTC, electricRGB commented
The test is passing locally.
<img width="782" alt="Screen Shot 2022-07-14 at 10 40 37 AM" src="https://user-images.githubusercontent.com/11182210/179009158-f2335322-d97b-4a9d-8385-032091801e97.png">

2022-07-14 14:42 UTC, merged