Populate uuid of rust-tabs sync metrics
mozilla-mobile/firefox-ios pull request #11285
Opened 2022-07-14 20:38 UTC by lougeniaC64

*Thank you for submitting a pull request, your contributions are greatly appreciated!*

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Please make sure you've run the test scheme and all the tests pass. If your changes affect existing tests please make sure to update the tests as well.

Below is the PR naming guidelines we follow:

https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide

2022-07-14 20:52 UTC, lougeniaC64 commented
All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.

1. What questions will you answer with this data?

  - This will help us to separately gauge the success rates of the native iOS tabs component and the application services tabs component as well as the client engine's sync success rates.

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?

  - We need to answer these questions to ensure that replacing the native tabs component with the application services tabs component doesn't result in degraded syncing for users. We also want to start tracking the sync success rates of the client engine ahead of its upcoming replacement.

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?

  - There are no other alternatives. 

4. Can current instrumentation answer these questions?

  - No. 

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki. 
Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.

Measurement Name | Measurement Description | Data Collection Category | Tracking Bug
-- | -- | -- | --
rust_tabs_sync.uid | The user's hashed Firefox Account ID. | interaction | https://mozilla-hub.atlassian.net/jira/software/c/projects/SYNC/boards/211?modal=detail&selectedIssue=SYNC-3170
rust_tabs_sync.incoming | Records incoming tabs record counts. applied is the number of incoming records that were successfully stored or updated in the local database. failed_to_apply is the number of records that were ignored due to errors. reconciled is the number of merged records. | interaction | https://mozilla-hub.atlassian.net/jira/software/c/projects/SYNC/boards/211?modal=detail&selectedIssue=SYNC-3170
rust_tabs_sync.outgoing | Records outgoing tabs record counts. uploaded is the number of records that were successfully sent to the server. failed_to_upload is the number of records that weren't uploaded, and will be retried on the next sync. | interaction | https://mozilla-hub.atlassian.net/jira/software/c/projects/SYNC/boards/211?modal=detail&selectedIssue=SYNC-3170
rust_tabs_sync.failure_reason | Records why the tabs sync failed. | interaction | https://mozilla-hub.atlassian.net/jira/software/c/projects/SYNC/boards/211?modal=detail&selectedIssue=SYNC-3170
clients_sync.uid | The user's hashed Firefox Account ID. | interaction | https://mozilla-hub.atlassian.net/jira/software/c/projects/SYNC/boards/211?modal=detail&selectedIssue=SYNC-3170
clients_sync.incoming | Records incoming clients record counts. applied is the number of incoming records that were successfully stored or updated in the local database. failed_to_apply is the number of records that were ignored due to errors. reconciled is the number of merged records. | interaction | https://mozilla-hub.atlassian.net/jira/software/c/projects/SYNC/boards/211?modal=detail&selectedIssue=SYNC-3170
clients_sync.outgoing | Records outgoing clients record counts. uploaded is the number of records that were successfully sent to the server. failed_to_upload is the number of records that weren't uploaded, and will be retried on the next sync. | interaction | https://mozilla-hub.atlassian.net/jira/software/c/projects/SYNC/boards/211?modal=detail&selectedIssue=SYNC-3170
clients_sync.failure_reason | Records why the clients sync failed. | interaction | https://mozilla-hub.atlassian.net/jira/software/c/projects/SYNC/boards/211?modal=detail&selectedIssue=SYNC-3170

6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

  - This collection is Glean so is documented [in the Glean Dictionary](https://dictionary.telemetry.mozilla.org/).

7. How long will this data be collected?

  - This collection has expiry '2023-01-01'

8. What populations will you measure?

  - All channels, countries, and locales. No filters.

9. If this data collection is default on, what is the opt-out mechanism for users?

  - These collections are Glean. The opt-out can be found in the product's preferences.

10. Please provide a general description of how you will analyze this data.

  - This data will be analyzed through existing and existing Redash dashboard.
 
11. Where do you intend to share the results of your analysis?

  - The results will be Mozilla internal.

12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?

  - No.

2022-07-14 21:15 UTC, lougeniaC64 commented
@travis79 Data review please? 🙏🏾

2022-07-15 16:05 UTC, travis79 requested changes
Since this involves a hashed unique identifier, I need to escalate this data-review to Trust & Legal. Could you could please update the review-request form in the comment to reflect that this identifier is "Category 4" data, and I'll work on getting this reviewed.  Thanks!

2022-07-15 16:05 UTC, travis79 commented on Sync/metrics.yaml
>        - technical
To get this in line with policy, we should add 
```suggestion
      - technical
      - highly_sensitive
```

2022-07-26 12:26 UTC, travis79 commented
@lougeniaC64 just letting you know that I haven't forgotten about this, I'm still waiting on Trust to take a look. I just pinged them yesterday to see what the status was.

2022-07-26 16:52 UTC, lougeniaC64 commented
> @lougeniaC64 just letting you know that I haven't forgotten about this, I'm still waiting on Trust to take a look. I just pinged them yesterday to see what the status was.

Thanks, @travis79!

2022-08-01 20:39 UTC, nishant2718 commented
FYI, given our release schedule, this PR will land as a v105 item unless bumped in priority.

2022-08-02 12:41 UTC, travis79 commented
> FYI, given our release schedule, this PR will land as a v105 item unless bumped in priority.

Thanks @nishant2718, I'm still waiting on Trust & Legal to review this, I'll ping them again but I will be out the rest of the week so it may be next week before I am able to complete the data-review for this.

2022-08-09 19:24 UTC, alavassanimozilla commented
No concern or issue from the Privacy/Legal perspective. Since  the collected "sync.sync_uid" is unidentifiable and can't be linked to a person or client ID (including other telemetry data), we can move forward.

2022-08-09 19:27 UTC, travis79 commented
> All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.
> 
>     1. What questions will you answer with this data?
> 
> 
>     * This will help us to separately gauge the success rates of the native iOS tabs component and the application services tabs component as well as the client engine's sync success rates.
> 
> 
>     2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
> 
> 
>     * We need to answer these questions to ensure that replacing the native tabs component with the application services tabs component doesn't result in degraded syncing for users. We also want to start tracking the sync success rates of the client engine ahead of its upcoming replacement.
> 
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
>     * There are no other alternatives.
> 
> 
>     4. Can current instrumentation answer these questions?
> 
> 
>     * No.
> 
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.    
>        Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.
> 
> 
> Measurement Name 	Measurement Description 	Data Collection Category 	Tracking Bug
> sync.sync_uid 	The user's hashed Firefox Account ID. Setting this field for the tabs data type now that it no longer uses legacy syncing. 	Category 4 	[mozilla-hub.atlassian.net/browse/SYNC-3237](https://mozilla-hub.atlassian.net/browse/SYNC-3237)
> 
>     6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
>     * This collection is Glean so is documented [in the Glean Dictionary](https://dictionary.telemetry.mozilla.org/).
> 
> 
>     7. How long will this data be collected?
> 
> 
>     * This collection has expiry '2023-01-01'
> 
> 
>     8. What populations will you measure?
> 
> 
>     * All channels, countries, and locales. No filters.
> 
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
>     * These collections are Glean. The opt-out can be found in the product's preferences.
> 
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
>     * This data will be analyzed through existing and existing Redash dashboard.
> 
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
>     * The results will be Mozilla internal.
> 
> 
>     12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
> 
> 
>     * No.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/).

2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, through the "Send Usage Data" preference in the application settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection to end 2023-01-01

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 4: Highly sensitive

5) Is the data collection request for default-on or default-off?

Default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

Not a new identifier, but an existing one being sent in the proper place and not connected or linked to other telemetry.

7) Is the data collection covered by the existing Firefox privacy notice?

Yes

8) Does the data collection use a third-party collection tool?

No

## Result

data-review+

2022-08-10 05:31 UTC, nbhasin2 approved these changes

2022-08-10 05:56 UTC, merged