Refactor FXIOS-4576 [v105] Pocket data adaptor
mozilla-mobile/firefox-ios pull request #11567
Opened 2022-08-10 14:50 UTC by lmarceau

# [FXIOS-4576](https://mozilla-hub.atlassian.net/browse/FXIOS-4576) https://github.com/mozilla-mobile/firefox-ios/issues/11315
- Add data adaptor for pocket section
- Moved some code into their own files
- Add tests for adaptor, adjust existing tests cases

2022-08-10 19:40 UTC, electricRGB approved these changes

2022-08-11 13:46 UTC, OrlaM requested changes

2022-08-11 13:46 UTC, OrlaM commented on Client/Frontend/Home/Pocket/PocketDataAdaptor.swift
> +    private var pocketStoriesViewModels = [PocketStandardCellViewModel]()
The adaptor shouldn't know anything about the view models or ideally anything view related. It looks like this model object is mostly constructed from the PocketStory data object so maybe you can store an array of those here and then convert to the view models in the PocketViewModel.

2022-08-11 15:02 UTC, OrlaM approved these changes

2022-08-11 16:11 UTC, merged