Localize FXIOS-5106 [v108]: Land share sheet strings
mozilla-mobile/firefox-ios pull request #12447
Opened 2022-11-21 21:58 UTC by dnarcese

2022-11-21 22:02 UTC, yoanarios approved these changes

2022-11-22 16:17 UTC, polymathruby requested changes

2022-11-22 16:25 UTC, polymathruby approved these changes

2022-11-22 17:09 UTC, polymathruby commented
BR is green.
<img width="1324" alt="Screen Shot 2022-11-22 at 12 09 06 PM" src="https://user-images.githubusercontent.com/11182210/203377659-e6c95015-ccde-4b76-bb65-e88f76c84d02.png">

2022-11-22 17:10 UTC, merged

2022-11-22 20:27 UTC, nishant2718 commented
🔥 !!