Refactor FXIOS-5286 [v109] Remove BVC dependence in inactiveTabsVM
mozilla-mobile/firefox-ios pull request #12518
Opened 2022-11-26 16:57 UTC by nishant2718

# [FXIOS-5286](https://mozilla-hub.atlassian.net/browse/FXIOS-5286)

TLDR: Removed dependence of BVC from InactiveTabViewModel by utilizing AppSessionManager.

2022-11-28 21:46 UTC, OrlaM requested changes

2022-11-29 15:34 UTC, OrlaM approved these changes

2022-11-29 17:04 UTC, yoanarios approved these changes

2022-11-29 18:17 UTC, nishant2718 commented
Failed in a smoketest on an unrelated note - so merging.

2022-11-29 18:17 UTC, merged