[WIP] Credit card capture PoC
mozilla-mobile/firefox-ios pull request #12787
Opened 2022-12-22 07:14 UTC by issammani

### This PR:

✅  Adds two way communication between ios and js.
✅  Adds webpack  plugin to resolve custom resource uris.
🚧  Extracts necessary logic from desktop to capture credit card fields.  <--- Current stage

⚠️ This is still a work in progress and is only public for visibility purposes.
⚠️ The [corresponding phabricator patch](https://phabricator.services.mozilla.com/D165374) ( also still a WIP )

2023-01-04 17:52 UTC, nbhasin2 commented
@issammani is this ready for review as I see WIP but is not a draft?

2023-01-17 11:34 UTC, issammani commented
@nbhasin2 @galich this PR is ready for review now. I will open a follow up PR to address some further work. But I think this should be enough for a PoC.

2023-01-17 14:42 UTC, lmarceau commented
FYI, build failed due to swiftlint errors described [here](https://github.com/mozilla-mobile/firefox-ios/pull/12787/checks?check_run_id=10699626106).

2023-01-18 23:54 UTC, nbhasin2 commented on Client/Frontend/TabContentsScripts/CreditCardHelper.swift
> +        ]
Since this is a POC we should leave this empty and fill it in when we are actually testing

2023-01-18 23:57 UTC, nbhasin2 commented on Client/Frontend/Browser/BrowserViewController.swift
> +        let creditCardHelper = CreditCardHelper(tab: tab)
We should wrap this around a feature flag as this is a POC and shouldn't get merged directly to Firefox iOS unless its feature is complete. 

Since it might take multiple PRs to reach there I would recommend adding a comment with Jira ticket and commenting out this piece of code.

2023-01-19 00:17 UTC, nbhasin2 commented
I also didn't see the use of `userscript manager` was that because of webpack compatibility issue?

2023-01-19 00:18 UTC, nbhasin2 requested changes
Thanks for the POC @issammani Although this is good but let's clean this up so it's mergeable. 

Ideally, we should add a component to encapsulate all details into a single area if possible but I understand that it might not be feasible in this PR. 

I would also recommend moving the POC over to SwiftFox where you can test your scripts much more freely as compared to Firefox iOS

Will ping you in slack for further discussion.

2023-01-22 16:59 UTC, issammani commented on Client/Frontend/TabContentsScripts/CreditCardHelper.swift
> +        ]
Commented and added a todo in [3c9d580](https://github.com/mozilla-mobile/firefox-ios/pull/12787/commits/3c9d5808b800870db1ee480c6926753b118774d1)

2023-01-22 16:59 UTC, issammani commented on Client/Frontend/Browser/BrowserViewController.swift
> +        let creditCardHelper = CreditCardHelper(tab: tab)
Commented and added a todo in [3c9d580](https://github.com/mozilla-mobile/firefox-ios/pull/12787/commits/3c9d5808b800870db1ee480c6926753b118774d1)

2023-01-22 17:05 UTC, issammani commented
@nbhasin2 following our discussion on the webpack plugin. This is needed for desktop imports that use uris. For instance, in this file: https://github.com/mozilla-mobile/firefox-ios/blob/3c9d5808b800870db1ee480c6926753b118774d1/Client/Assets/CC_Script/FormAutofillHeuristics.shared.mjs#L1-L4

2023-01-31 19:10 UTC, nbhasin2 commented on Client/Frontend/TabContentsScripts/CreditCardHelper.swift
> +    func userContentController(_ userContentController: WKUserContentController, didReceiveScriptMessage message: WKScriptMessage) {
```suggestion
    func userContentController(_ userContentController: WKUserContentController,
                               didReceiveScriptMessage message: WKScriptMessage) {
```

2023-01-31 19:32 UTC, nbhasin2 commented on Client/Frontend/TabContentsScripts/CreditCardHelper.swift
> +            let fillCreditCardInfoCallback = "window.__firefox__.CreditCardHelper.fillCreditCardInfo('\(String(data: jsonData, encoding: .utf8)!)')"
```suggestion
            let jsonData = try JSONSerialization.data(withJSONObject: "asd")
            guard let jsonDataVal = String(data: jsonData, encoding: .utf8) else { return }
            let fillCreditCardInfoCallback = "window.__firefox__.CreditCardHelper.fillCreditCardInfo('\(jsonDataVal)')"
```

2023-02-01 20:36 UTC, issammani commented
> @issammani Skipped the js files as those will get updated later on but added a few nits to streamline the code
> 
> You can either take my suggestions or modify it yourself and after BR is green we are good to push :)

@nbhasin2 thanks for the suggestions and updating the PR. Looks good from my side. BR is failing though. I am tempted to push an empty commit just to have run once again. Do we have a better way to do so ?

2023-02-01 20:39 UTC, nbhasin2 commented
@issammani https://app.bitrise.io/build/54a6820e-666f-413d-997c-0310b39c3ade

I started another build, no idea why it failed 🤷🏼‍♂️ 

Try if you can run it locally as this passed before.

2023-02-01 21:41 UTC, isabelrios commented
<!--
  0 failure: 
  0 warning: 
  3 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 29.03%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 3 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 9 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 25.72
| File | Coverage ||
| --- | --- | --- |
CreditCardHelper.swift | 0.0% | ⚠️
BrowserViewController.swift | 20.61% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against a7476f34feb9b76df0555b7e5c10d39591eb7ac0
</p>

2023-02-02 06:29 UTC, nbhasin2 commented
The failed test has nothing to do with this PR. 

Will look into it tomorrow but most likely merge it in as it could be a random failure from BR

2023-02-03 04:54 UTC, merged