Add FXIOS-5633 [v111] Sentry in logger package
mozilla-mobile/firefox-ios pull request #13134
Opened 2023-02-03 22:01 UTC by lmarceau

## [FXIOS-5633](https://mozilla-hub.atlassian.net/browse/FXIOS-5633) https://github.com/mozilla-mobile/firefox-ios/issues/13012
- Add Sentry integration to Logger package, keeping only interface we'll use in the new integration
- Remove unused import in BVC
- Had to move some extension code (including AppConstants and AppInfo). There's follow-up work for this in [FXIOS-5698](https://mozilla-hub.atlassian.net/browse/FXIOS-5698) since we want to keep BrowserKit as generic as possible.
- Multiple `import Common` needed to be added due to the extension code that was moved
- Add unit tests

2023-02-06 21:14 UTC, mte-test commented
<!--
  0 failure: 
  0 warning: 
  3 messages
  7 markdown notices
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Project coverage: 29.21%</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Edited 76 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 9 files</td>
    </tr>
  </tbody>
</table>

## Client.app: Coverage: 26.02
| File | Coverage ||
| --- | --- | --- |
SyncContentSettingsViewController.swift | 0.0% | ⚠️
main.swift | 80.0% | ✅
AppSettingsTableViewController.swift | 0.0% | ⚠️
UITestAppDelegate.swift | 0.0% | ⚠️
CustomAppActivity.swift | 0.0% | ⚠️
DefaultBrowserOnboardingViewController.swift | 0.0% | ⚠️
AdjustHelper.swift | 0.0% | ⚠️
WallpaperURLProvider.swift | 71.43% | ✅
WebServer.swift | 0.0% | ⚠️
NotificationManager.swift | 74.15% | ✅
URLBarView.swift | 48.78% | ⚠️
URIFixup.swift | 84.48% | ✅
Experiments.swift | 59.04% | ✅
TabFileManager.swift | 100.0% | ✅
AppLaunchUtil.swift | 0.0% | ⚠️
LegacyWallpaperNetworkUtility.swift | 0.0% | ⚠️
WebServerUtil.swift | 0.0% | ⚠️
SearchBarSettingsViewModel.swift | 93.98% | ✅
AppVersionUpdateCheckerProtocol.swift | 0.0% | ⚠️
SessionData.swift | 69.83% | ✅
AppSettingsOptions.swift | 0.0% | ⚠️
GleanPlumbMessageUtility.swift | 29.63% | ⚠️
Profile.swift | 22.39% | ⚠️
TabLocationView.swift | 45.36% | ⚠️
FirefoxTabContentBlocker.swift | 0.0% | ⚠️
TabManager.swift | 46.91% | ⚠️
Tab.swift | 38.01% | ⚠️
BrowserViewController.swift | 20.61% | ⚠️
TelemetryWrapper.swift | 65.89% | ✅
SimpleTab.swift | 68.85% | ✅
UpdateViewModel.swift | 71.58% | ✅
CoreFlaggableFeature.swift | 100.0% | ✅
WidgetKitTopSiteModel.swift | 0.0% | ⚠️


## CredentialProvider.appex: Coverage: 18.92
| File | Coverage ||
| --- | --- | --- |
Profile.swift | 22.39% | ⚠️


## NotificationService.appex: Coverage: 20.13
| File | Coverage ||
| --- | --- | --- |
Profile.swift | 22.39% | ⚠️
NotificationService.swift | 0.0% | ⚠️


## ShareTo.appex: Coverage: 29.39
| File | Coverage ||
| --- | --- | --- |
InitialViewController.swift | 0.0% | ⚠️
Profile.swift | 22.39% | ⚠️
URIFixup.swift | 84.48% | ✅


## WidgetKitExtension.appex: Coverage: 22.33
| File | Coverage ||
| --- | --- | --- |
WidgetKitTopSiteModel.swift | 0.0% | ⚠️
SessionData.swift | 69.83% | ✅
TabFileManager.swift | 100.0% | ✅
SimpleTab.swift | 68.85% | ✅
AppInfo.swift | 41.18% | ⚠️


## libAccount.a: Coverage: 59.36
| File | Coverage ||
| --- | --- | --- |
RustFirefoxAccounts.swift | 57.52% | ✅
KeyBundle.swift | 85.59% | ✅
PushNotificationSetup.swift | 0.0% | ⚠️


## libSyncTelemetry.a: Coverage: 35.48
| File | Coverage ||
| --- | --- | --- |
SyncTelemetry.swift | 0.0% | ⚠️

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 4321001b1a2d678108849ee37410940b2a079367
</p>

2023-02-06 22:00 UTC, lmarceau commented
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/5b0c7791-9a32-4552-94a9-147d08655bc7)

2023-02-07 21:47 UTC, OrlaM commented on BrowserKit/Sources/Common/Extensions/DictionnaryExtension.swift
> +public extension Dictionary {
The file has an extra n in it.

2023-02-07 21:51 UTC, OrlaM requested changes

2023-02-07 21:51 UTC, OrlaM commented on BrowserKit/Sources/Logger/DefaultLogger.swift
>                      sendToSentry: Bool = false,
We can infer if the log should be sent to sentry by the log level. If it's fatal we always send it. If it's lower we could also send a breadcrumb.

2023-02-07 21:51 UTC, OrlaM commented on BrowserKit/Sources/Logger/SentryWrapper.swift
> +        let shouldSendBeta = AppConstants.BuildChannel == .beta && level.isGreaterOrEqualThanLevel(.warning)
Be careful setting this to warning if we are still sending many of the logs that were there before. Even if it's only beta some of them were spammy enough to cause problems.

2023-02-08 14:31 UTC, OrlaM approved these changes

2023-02-08 14:38 UTC, merged