Bugfix FXIOS-5955 [v112] Fix wrong selected passwords after filtering
mozilla-mobile/firefox-ios pull request #13546
Opened 2023-03-11 14:35 UTC by whitelips

[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-5955)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/13530)

### Description
LoginRecords are saved before query and they are converted to IndexPaths after query

2023-03-13 19:56 UTC, nishant2718 commented
Hello! There was a recent patch in the general area around Logins you're working in. Could you please rebase to get that commit into your PR? It prevents crashing due to a Dispatches having varying priority.

2023-03-14 14:12 UTC, nishant2718 commented
Thanks! I'll have a look later today and get back to you.

2023-03-22 21:09 UTC, nishant2718 commented
I apologize for the delay. It looks like there's a regression this PR may introduce. 

On the passwords screen
1. Hit edit
2. Hit Select All on the bottom
3. Go to filter and search for something
4. Then hit Cancel

The filtered items list remains selected but the others now appear to be unselected (I believe they are selected, and hitting delete will delete all of them). 

Is it possible to adjust the PR to make it behave as Production does? @whitelips

2023-03-22 21:09 UTC, nishant2718 requested changes
See the comment above about the regression.

2023-04-29 14:07 UTC, whitelips commented
This problem couldn't be temporarily solved using a LoginRecord, as the current code is based on IndexPath.
Later, I will attempt to fix this issue again.

2023-04-29 14:07 UTC, closed without merging