Refactor MTE-628 v113 Re-enable failing smoke tests
mozilla-mobile/firefox-ios pull request #13630
Opened 2023-03-17 20:01 UTC by SimonBasca

[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

### Still needs addresing
- testDeleteHistoryEntryBySwiping() - still needs to be check if it fails on M1
- testTopSitesRemoveAllExceptDefaultClearPrivateData() - Database not loading

### Pull requests checks where applicable
- testJumpBackIn() - passing locally
- testCloseTabFromLongPressTabsButton() - passing locally
- testLongTapTabCounter() - passing locally
- testPinToTop() - passing locally

2023-03-17 20:15 UTC, mte-test commented
<!--
  0 failure: 
  1 warning:  Print() function ...
  2 messages
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Print() function seems to be used in file Tests/XCUITests/PhotonActionSheetTest.swift at line 25. Please remove this usage from production code or use BrowserKit Logger.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Edited 4 files</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Created 0 files</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against 52cd3fa0a13958ad61fb500184f3e621663a4cdb
</p>

2023-03-20 04:14 UTC, clarmso commented on Tests/XCUITests/HistoryTests.swift
> -            print(app.debugDescription)
😬 Yes, remove this line.

2023-03-20 04:34 UTC, clarmso commented on Tests/XCUITests/HomePageSettingsUITest.swift
> +    func testJumpBackIn() {
LGTM.

2023-03-20 04:57 UTC, clarmso commented on Tests/XCUITests/TopTabsTest.swift
> +            app.buttons["Show Tabs"].press(forDuration: 1)
The test fails on my end here. Here's the simulator's screen at this point. 😞 
![Simulator Screen Shot - iPhone 14 - 2023-03-20 at 00 55 39](https://user-images.githubusercontent.com/1740517/226250327-6823378b-1a13-4980-b002-3dd355287d96.png)

2023-03-20 05:04 UTC, clarmso commented on Tests/XCUITests/PhotonActionSheetTest.swift
> +    func testPinToTop() {
LGTM

2023-03-20 05:05 UTC, clarmso requested changes
testLongTapTabCounter is not passing on my end.

2023-03-20 16:09 UTC, clarmso commented on Tests/XCUITests/TopTabsTest.swift
> +
```suggestion
waitForExistence(app.collectionViews.cells["TopSitesCell"])
```
Adding this line can ensure that the screen is loaded before attempting to close the keyboard.

2023-04-11 08:33 UTC, SimonBasca commented
> testLongTapTabCounter fails on my end.

Should be passing now.

2023-04-12 13:17 UTC, SimonBasca commented
@clarmso all checks are green. Could your review the changes and merge the pull reqeust when you have a chance? Thank you.

2023-04-18 15:00 UTC, clarmso approved these changes
🚀 🚀 🚀

2023-04-18 15:02 UTC, merged