Add FXIOS-6016 [114] #13660 - Add deeplink support into coordinators
mozilla-mobile/firefox-ios pull request #14123
Opened 2023-04-25 12:06 UTC by razvanlitianu

[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6016)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/13660)

### Description
Create a method to find the coordinator that can handle route. Add method for handling the route.

### Pull requests checks where applicable
- [ ] Fill in the three TODOs above (tickets number and description of your work)
- [ ] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

2023-04-25 15:25 UTC, lmarceau approved these changes

2023-04-25 15:25 UTC, lmarceau commented on Client/Coordinators/Coordinator.swift
> +    /// - Note: This extension assumes that the `Coordinator` class conforms to the `Coordinator` protocol, which has a method `handle(route:)` that returns a Boolean value indicating whether the coo
I think that note is implied since we're extending the Coordinator, and not necessary to explain here
```suggestion
```

2023-04-25 15:28 UTC, lmarceau requested changes

2023-04-26 08:33 UTC, razvanlitianu commented
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/bfb9267e-7e52-4a75-98f7-2d7f797b1098).

<img width="1081" alt="Screenshot 2023-04-26 at 11 33 11" src="https://user-images.githubusercontent.com/26011662/234517898-04ee4b93-67cf-4ed1-bcf4-24438f4ebdea.png">

2023-04-26 13:52 UTC, lmarceau approved these changes

2023-04-26 13:52 UTC, merged