Refactor FXIOS-6465 [v115] Consistency use of accessibility identifiers for both iPhone and iPad navigation bar
mozilla-mobile/firefox-ios pull request #14595
Opened 2023-05-26 17:51 UTC by lmarceau

[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-6465)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/14539)

### Description
Making sure we're consistent on a11y identifiers between iPad and iPhone.
- The back button was called `"URLBarView.backButton"` or `"TabToolbar.backButton"`. Now we always refer to it as `"TabToolbar.backButton"`
- The tabs button was called `"URLBarView.tabsButton"`, `"TopTabsViewController.tabsButton"` or `"TabToolbar.tabsButton"`. Now we always refer to it as `"TabToolbar.tabsButton"`
- The new tab button was called `"TopTabsViewController.newTabButton"`, `"TabToolbar.addNewTabButton"` or `"newTabButtonTabTray"`. Now we always refer to it as `"TabToolbar.addNewTabButton"`
- Made sure all toolbar/url bar have their a11y identifiers.
- Made sure the multistate button is properly identified with the purpose it has.
- Adjusted the UI tests where needed. Hopefully I didn't miss any, I have trouble running UITests locally (but can run XCUITests normally).

### Pull requests checks where applicable
- [X] Fill in the three TODOs above (tickets number and description of your work)
- [X] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [X] Unit tests written and passing
- [ ] Documentation / comments for complex code and public methods

2023-05-26 19:43 UTC, lmarceau commented
Those tests are failing, @clarmso I would need some help it seems to figure out why 😬🙏
<img width="517" alt="Screenshot 2023-05-26 at 3 42 43 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/11338480/157bbde6-12cf-44f4-927e-4cd4e39004d5">

2023-05-29 04:48 UTC, clarmso commented
> Those tests are failing, @clarmso I would need some help it seems to figure out why 😬🙏 <img alt="Screenshot 2023-05-26 at 3 42 43 PM" width="517" src="https://user-images.githubusercontent.com/11338480/241310166-157bbde6-12cf-44f4-927e-4cd4e39004d5.png">

Bitrise's test report tells me that the app may not be running. 😞 The tests should be passing on main. Looking... 👓 

https://addons-testing.bitrise.io/builds/25470e2d-b7d5-4e91-bef0-eae827374e71/testreport/a2968071-1919-47a3-a14a-9c59fb21aa4b/testsuite/0/testartifacts?status=failed

2023-05-29 05:06 UTC, clarmso commented
Somewhat related: By running the tests in parallel, we don't have the detailed logs for individual tests. We only know the pass/fail and not where exactly the test failed.

Note for self: Let me think about how the impact on disabling parallel testing on bitrise.

2023-05-29 05:07 UTC, clarmso requested changes
Unable to locate `TabToolbar.homeButton` is the cause of the test failure.

2023-05-29 17:22 UTC, lmarceau commented
Green build [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/da636282-ce89-40ce-afa4-9675cf278038) 🎉 Let me know if the fix I propose is ok

2023-05-30 09:11 UTC, thatswinnie reviewed
🎉🙏🏼

2023-05-30 09:11 UTC, thatswinnie commented on Tests/XCUITests/NavigationTest.swift
>          if iPad() {
I think we could simplify the if statement - the only difference seems to be that for the iPad we tap the url field.

2023-05-30 09:11 UTC, thatswinnie commented on Tests/XCUITests/NavigationTest.swift
>          if iPad() {
I think we could get rid of the if statement here.

2023-05-30 09:11 UTC, thatswinnie commented on Tests/XCUITests/NavigationTest.swift
>          if iPad() {
Same here: I don't think we need the if anymore.

2023-05-30 13:37 UTC, clarmso commented
👋🏼 Let me run the full functional test suite, which is not run on Bitrise, on both iPhone and iPad from my end. I'll report back later today!

2023-05-30 15:50 UTC, thatswinnie approved these changes

2023-05-30 17:15 UTC, clarmso commented on Tests/XCUITests/BrowsingPDFTests.swift
> -        if iPad() {
😆 We do have lots of `if` statement checking for `iPad()`.

2023-05-30 18:19 UTC, clarmso commented
Please address the following test failures from the full functional test suite (iPhone 14): 🙇🏼 
```
HomeButtonTests.testGoHome()
SearchTests.testSearchIconOnAboutHome()
```

2023-05-30 19:32 UTC, clarmso commented
🎉 All full functional tests pass on iPad.

2023-05-30 21:09 UTC, lmarceau commented
Build is green [here](https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/a2c50334-4487-44b5-a04f-b5603273260e)

2023-05-31 10:10 UTC, isabelrios commented
Oh sorry I re-run just the failed step from github UI and that failed and cause the general Bitrise to go red although it is green...
I think @clarmso you need to approve the changes now so that the merge is unblocked...as the review still appear as changes requested

2023-05-31 11:48 UTC, clarmso approved these changes

2023-05-31 13:53 UTC, clarmso commented
All full functional tests and all smoke tests pass on both iPhone and iPad.

The change should not affect the Sync Integration tests.

👍🏼 @lmarceau Please merge this PR.

2023-05-31 15:16 UTC, merged