Refactor FXIOS-14980 [v116] RecentlyClosedTabsPanel with Themeable protocol.
mozilla-mobile/firefox-ios pull request #15163
Opened 2023-06-23 09:57 UTC by FilippoZazzeroni

[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/14980)

### Description

Refactor `RecentlyClosedTabsPanel` with `Themeable` protocol.

### Pull requests checks where applicable
- [x] Fill in the three TODOs above (tickets number and description of your work)
- [x] The PR name follows our [naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Accessibility implemented and tested (minimum Dynamic Text and VoiceOver)
- [ ] Unit tests written and passing
- [x] Documentation / comments for complex code and public methods

2023-06-26 15:52 UTC, lmarceau requested changes
The color `RecentlyClosedPanelUX.IconBorderColor.cgColor` should also be set with the new theming system. It shouldn't be part of that UX struct, and instead rely on setting the color from the `TwoLineImageOverlayCell` which is already following the theme applicable protocol. So just calling `applyTheme` on that cell in `cellForRowAt` should do the trick.

2023-06-26 16:10 UTC, FilippoZazzeroni commented on Client/Frontend/LoginManagement/LoginListViewController.swift
> +        }
I forgot to add it in a previous PR https://github.com/mozilla-mobile/firefox-ios/pull/14957, i saw in the login list that when the search result controller's text field gets focus the selection button was still visible also if the table view wasn't in editing mode.

2023-06-26 16:11 UTC, FilippoZazzeroni commented
> The color `RecentlyClosedPanelUX.IconBorderColor.cgColor` should also be set with the new theming system. It shouldn't be part of that UX struct, and instead rely on setting the color from the `TwoLineImageOverlayCell` which is already following the theme applicable protocol. So just calling `applyTheme` on that cell in `cellForRowAt` should do the trick.

Ok perfect i'm going to fix it.

2023-06-26 17:17 UTC, lmarceau commented
LGTM, could you add some screenshots of what the view looks like with the theme change? So we can get approval of our UX designer

2023-06-26 17:27 UTC, FilippoZazzeroni commented
Yes sure.

2023-06-26 17:42 UTC, lmarceau approved these changes

2023-06-26 17:47 UTC, FilippoZazzeroni commented
![Simulator Screenshot - iPhone 14 Pro - 2023-06-26 at 19 39 12](https://github.com/mozilla-mobile/firefox-ios/assets/55580351/30c139e4-e5b1-47fe-87b1-2d4d169e17ad)
![Simulator Screenshot - iPhone 14 Pro - 2023-06-26 at 19 45 03](https://github.com/mozilla-mobile/firefox-ios/assets/55580351/b76f9eba-f6bf-409d-aa66-ea383aa51b37)

2023-06-26 18:07 UTC, lmarceau commented
Tagging @cwzilla for UX review 🙏

2023-06-26 21:12 UTC, nbhasin2 commented
@lmarceau feel free to hit merge after UX review, this lgtm

2023-06-26 23:21 UTC, cwzilla commented
What is the background color used in light mode? It should be Layer 1. Everything else looks good!

2023-06-27 12:11 UTC, FilippoZazzeroni commented
@cwzilla the table view background color was set to layer6 now it's layer1.

![Simulator Screenshot - iPhone 14 Pro - 2023-06-27 at 14 08 31](https://github.com/mozilla-mobile/firefox-ios/assets/55580351/2f2cb348-a2d2-492d-8dff-406cb7108820)
![Simulator Screenshot - iPhone 14 Pro - 2023-06-27 at 14 08 57](https://github.com/mozilla-mobile/firefox-ios/assets/55580351/cad5d64b-50a1-4d0e-83fd-ec529e6402e6)

2023-06-27 17:52 UTC, merged