BugFix FXIOS-7316 [v119] history panel not showing recent history
mozilla-mobile/firefox-ios pull request #16332
Opened 2023-09-10 08:06 UTC by FilippoZazzeroni

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7316)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16242)

## :bulb: Description
Bugfix `HistoryPanel` not showing recent history.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed I updated documentation / comments for complex code and public methods

2023-09-11 15:34 UTC, clarmso commented
@lmarceau I'm running the full functional test suite on my end. Please do not merge this PR before I confirm the issue is fixed and does not introduce new regressions.

2023-09-11 16:45 UTC, clarmso commented
> @lmarceau I'm running the full functional test suite on my end. Please do not merge this PR before I confirm the issue is fixed and does not introduce new regressions.

I confirmed that this PR does not introduce new regressions via running the full functional test suite and the sync integration tests. 👍🏼

2023-09-11 18:29 UTC, lmarceau commented on Client/Frontend/Library/HistoryPanel/HistoryPanel.swift
> +        viewModel.shouldResetHistory = true
Wondering if this should be behind the `CoordinatorFlagManager.isLibraryCoordinatorEnabled` flag if we keep this (see other comments)

2023-09-11 18:29 UTC, lmarceau commented on Client/Frontend/Library/LibraryViewController/LibraryViewController.swift
> +        if let panelVC = panelVC as? LibraryPanel {
This works both with and without coordinators?

2023-09-11 18:29 UTC, lmarceau commented on Client/Coordinators/Library/LibraryCoordinator.swift
> +        }
We cannot reuse existing child coordinators? Instead of recreating them

2023-09-11 18:29 UTC, lmarceau commented on Client/Coordinators/Library/LibraryCoordinator.swift
> +        router.setRootViewController(libraryViewController)
So I'm afraid by recreating the library VC we're going to lose some of the states saved in for example the bookmarks panel. Can you check this still works (the section we're in should be kept). Hence why this was saved and LibraryCoordinator isn't niled after the user leaves the library panels.

2023-09-12 15:31 UTC, lmarceau commented
> @lmarceau There's no new regressions introduced by this PR (via full functional test suite). 🎉 Please feel free to review the changes.

There's some changes needed after review, once done we can rerun the test suites.

2023-09-12 15:31 UTC, lmarceau requested changes
As discussed above in comments

2023-09-12 15:37 UTC, clarmso commented
> > @lmarceau There's no new regressions introduced by this PR (via full functional test suite). 🎉 Please feel free to review the changes.
> 
> There's some changes needed after review, once done we can rerun the test suites.

I have pulled the changes and ran the tests again.

2023-09-12 15:53 UTC, FilippoZazzeroni commented
@clarmso i didn't pushed the changes, i will do it by the end of the day

2023-09-13 14:18 UTC, lmarceau approved these changes
One small comment for swiftlint, otherwise LGTM

2023-09-13 15:09 UTC, lmarceau commented
@clarmso all looks good on my side, can you recheck all is good on yours so we can hopefully merge this PR?

2023-09-13 19:55 UTC, clarmso approved these changes

2023-09-13 20:01 UTC, clarmso commented
@lmarceau All good on the XCUITest.

2023-09-13 20:40 UTC, merged