Remove FXIOS-7673 [v121] Remove SnapKit from SearchViewController
mozilla-mobile/firefox-ios pull request #17420
Opened 2023-11-22 11:14 UTC by pelumy

…roller

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-TODO)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/TODO)

## :bulb: Description

- Removed `SnapKit` constraint on `SearchViewController` in the `BrowserViewController`
- Replaced `SnapKit` constraint with `NSLayoutConstraint`

Video showing how it works after change:

https://github.com/mozilla-mobile/firefox-ios/assets/54324355/10beb295-ead5-4941-b68f-97f44f183911

## :pencil: Checklist
You have to check all boxes before merging
- [x ] Filled in the above information (tickets numbers and description of your work)
- [x ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [x ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

2023-11-22 13:34 UTC, lmarceau reviewed
Hello @pelumy! Thank you for your work, this is great but we would like to remove as well the snapkit constraints from the `SearchViewController.swift` file if possible (if you search for `snp.` you'll see 10 matches in there). Do you want to look into those too? Can be done either with this PR or another one, as you wish!

2023-11-22 13:37 UTC, pelumy commented
> Hello @pelumy! Thank you for your work, this is great but we would like to remove as well the snapkit constraints from the `SearchViewController.swift` file if possible (if you search for `snp.` you'll see 10 matches in there). Do you want to look into those too? Can be done either with this PR or another one, as you wish!

I will include the changes in this PR. Thanks for pointing it out.

2023-11-23 17:04 UTC, lmarceau requested changes
Hello! Couple of things:

With the latest changes, it seems there are some issues with top and bottom URL bar when showing the search view. We should be seeing three things with either top or bottom URL bar when we start typing for a search:
    1. The URL bar still need to be shown
    2. The search view controller shows the suggestions when we type
    3. The search engines suggestions bar should be appearing on top of the keyboard

I'm not seeing 1 and 3 when typing:
![Simulator Screenshot - iPhone 15 Plus - 2023-11-23 at 12 00 40](https://github.com/mozilla-mobile/firefox-ios/assets/11338480/cd0b9f90-69a2-4dbf-b01d-d30c56e7c351)

I think this is due to how the constraints were changed in a couple of places. With SnapKit, constraints were **either** applied to top or bottom of certain elements depending on if we have the bottom or top URL bar. With the current PR, constraints are applied to top and bottom all the time, so I think this is where the problem lies. Let me know if there's any more details needed 🙏

2023-11-23 23:09 UTC, pelumy commented
> Hello! Couple of things:
> 
> With the latest changes, it seems there are some issues with top and bottom URL bar when showing the search view. We should be seeing three things with either top or bottom URL bar when we start typing for a search: 1. The URL bar still need to be shown 2. The search view controller shows the suggestions when we type 3. The search engines suggestions bar should be appearing on top of the keyboard
> 
> I'm not seeing 1 and 3 when typing: ![Simulator Screenshot - iPhone 15 Plus - 2023-11-23 at 12 00 40](https://user-images.githubusercontent.com/11338480/285272724-cd0b9f90-69a2-4dbf-b01d-d30c56e7c351.png)
> 
> I think this is due to how the constraints were changed in a couple of places. With SnapKit, constraints were **either** applied to top or bottom of certain elements depending on if we have the bottom or top URL bar. With the current PR, constraints are applied to top and bottom all the time, so I think this is where the problem lies. Let me know if there's any more details needed 🙏

Thanks for pointing it out. I will fix this issue.

2023-11-24 00:23 UTC, pelumy commented on Client/Frontend/Browser/BrowserViewController.swift
> +        searchController.view.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = !isBottomSearchBar
@lmarceau , I can see that line 1086 and 1087 is where the issue is coming from. What I'm trying to figure out is why the search engine view disappears when I remove the previous line 1080 `searchController.view.snp.makeConstraints { make in }`. But with this line of code and the new constraints, the search engines show up.

2023-11-29 16:45 UTC, lmarceau commented
Hello! Thanks @pelumy this great work! I pulled in the changes and there seems to be one thing left. With the top bar enabled, if I try to scroll on the search view controller the keyboard is being dismissed. The search view controller should then take the space so we can see the result full page, as it's done on `main`. I tested with bottom URL bar and all seemed good over there 👍 

Thank you, let me know if there's anything!

2023-12-11 20:45 UTC, cyndichin approved these changes
thanks for the changes! looks good on my side :)

2023-12-12 18:50 UTC, lmarceau approved these changes
Great work!! 🎉

2023-12-12 20:34 UTC, merged