Rgb/8183 nimbus script fix
mozilla-mobile/firefox-ios pull request #18199
Opened 2024-01-16 21:40 UTC by adudenamedruby

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8183)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/18198)

## :bulb: Description
It wasn't working because "The Merge" changed relative paths.
Now, it is.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

2024-01-17 20:06 UTC, lmarceau approved these changes

2024-01-17 20:08 UTC, lmarceau requested changes
Oh wait, just realized. I don't think those are used anymore, so we could remove them ?

2024-01-17 20:17 UTC, adudenamedruby commented
What aren't used anymore? the features that got added to nimbus.fml.yaml in this PR?

2024-01-19 15:33 UTC, lmarceau approved these changes

2024-01-19 15:41 UTC, merged