Add FXIOS-8094 [v123.1] Private browsing shortcut on homepage
mozilla-mobile/firefox-ios pull request #18518
Opened 2024-02-01 15:39 UTC by cyndichin

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-8094)

## :bulb: Description
Add private browsing shortcut on homepage to toggle between normal and private mode
* Created `HomepageHeaderCell` that contains the header logo and the new private mode shortcut toggle button
* Update padding as discussed with design
* Added telemetry for
* Using existing telemetry 

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [x] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

2024-02-01 15:55 UTC, cyndichin commented
Some context, it seems that on Android it's easier to add multiple colors to a vector image. However, on iOS it is easier if we have the assets with the colors as opposed to trying to rely on the icon library without the colors.

I had programmatically created the circle as opposed to getting the asset from design, which makes it more flexible if we wanted to change colors. Wanted to get some eyes on this PR first and can create a new PR or update this one with using the asset if that's preferred. Thanks!  cc: @thatswinnie

2024-02-01 20:08 UTC, cyndichin commented
@adudenamedruby 

# Request for data collection review form

1) What questions will you answer with this data?

- How often are our users engaging with the private mode toggle button and switching between normal / private mode

2) Why does Mozilla need to answer these questions?  Are there benefits for users? 
Do we need this information to address product or business requirements? Some example responses:

- This data will help us understand user engagement with the new shortcut feature. If we see a spike in users interacting with this button, it shows whether this feature is relevant for the users or not, which can help support business decisions to provide a better experience for users. Also, we can understand better how often users are switching between modes.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

- There are other ways to switch between private and normal mode, but this is a new convenient way on iPhone.

4) Can current instrumentation answer these questions?

- No, not related to this toggle button.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td>Records when the private browsing mode icon is toggled on homepage.</td>
    <td>Category 2: Interaction data</td>
    <td>https://github.com/mozilla-mobile/firefox-ios/issues/18522</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
https://dictionary.telemetry.mozilla.org/apps/firefox_ios

7) How long will this data be collected?  Choose one of the following:
Currently set to expire 2024-06-01

8) What populations will you measure?

* Which release channels?
All

* Which countries?
All

* Which locales?
All

9) If this data collection is default on, what is the opt-out mechanism for users?
The user can opt out

10) Please provide a general description of how you will analyze this data.
Glean

11) Where do you intend to share the results of your analysis?
Glean and felt privacy team

12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:
No third party tools

2024-02-01 20:31 UTC, cyndichin commented on firefox-ios/Client/Frontend/Home/LogoHeader/HomepageHeaderCell.swift
> +        privateModeButton.insertSubview(circularView, belowSubview: privateModeButton.imageView ?? privateModeButton)
I am very iffy about this piece of code, let me know if you see a better suggestion in placing the circle view behind the image view. Leaving this PR in draft for now as I may come with fresher eyes tomorrow, but would like to get some early feedback in general!

2024-02-02 12:48 UTC, thatswinnie commented on firefox-ios/Client/Frontend/Home/LogoHeader/HomepageHeaderCell.swift
> +        button.accessibilityHint = .TabTrayToggleAccessibilityHint
The button should also have an a11y id.

2024-02-02 15:15 UTC, cyndichin commented on firefox-ios/Client/Frontend/Home/LogoHeader/HomepageHeaderCell.swift
> +        privateModeButton.insertSubview(circularView, belowSubview: privateModeButton.imageView ?? privateModeButton)
refactored and removed this code

2024-02-02 15:15 UTC, cyndichin commented on firefox-ios/Client/Frontend/Home/LogoHeader/HomepageHeaderCell.swift
> +        button.accessibilityHint = .TabTrayToggleAccessibilityHint
updated, thanks!

2024-02-02 15:33 UTC, cyndichin commented
Experience on split view will be addressed in a separate PR.

2024-02-02 15:34 UTC, thatswinnie approved these changes

2024-02-02 16:40 UTC, adudenamedruby approved these changes

2024-02-02 18:14 UTC, clarmso commented
Let me close and reopen this PR to trigger another Bitrise approval request. Stay tuned!

2024-02-02 18:14 UTC, clarmso commented
Reopen to trigger Bitrise. 🤞🏼

2024-02-03 04:33 UTC, clarmso commented
🙅🏼  For this pipeline, only `determine_apps_affected` is run after merging from main.
https://app.bitrise.io/app/6c06d3a40422d10f/pipelines/af000647-e4f1-4fc8-9fd8-7ba64a04ea7f

2024-02-03 04:33 UTC, clarmso commented
Close and reopen the PR to trigger Bitrise.

2024-02-03 04:38 UTC, clarmso commented
🙅🏼‍♀️ `build_applications` is still not run: https://app.bitrise.io/build/23644183-79b9-430d-94a6-fd4886c8afc4

2024-02-03 04:57 UTC, clarmso commented on bitrise.yml
> +                echo "$app"
The change in this line seems to trigger the `build_applications` step in the pipeline. I will remove this.

2024-02-03 05:42 UTC, clarmso commented on firefox-ios/Client/Frontend/Home/LogoHeader/HomepageHeaderCell.swift
> +        let maskImage = UIImage(named: ImageIdentifiers.privateMaskSmall)?.withRenderingMode(.alwaysTemplate)
@cyndichin Please check if `ImageIdentifiers.privateMaskSmall` exists.

2024-02-03 05:43 UTC, clarmso requested changes
I can't build on the command line on my end. Please ensure that you can build on your end. 🙇🏼‍♀️

2024-02-05 14:17 UTC, cyndichin commented
@clarmso rebased on latest and everything looks good now! let me know if there is any other concerns! thank you for reviewing :)

2024-02-05 15:12 UTC, merged