Pass in a data path to the suggest component
mozilla-mobile/firefox-ios pull request #18661
Opened 2024-02-09 21:01 UTC by bendk

## :scroll: Tickets
[Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1879647)

## :bulb: Description
This sends a data path to the suggest component, which we will need once we start storing persistent data.

This is a pretty simple change, but I wrote it completely blind and also I don't have enough iOS knowledge to know if I'm choosing the correct path here.  I need someone to a) run the tests and see if they pass and b) check that I'm putting the persistent data in the right directly.

## :pencil: Checklist
You have to check all boxes before merging
- [ ] Filled in the above information (tickets numbers and description of your work)
- [ ] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed I updated documentation / comments for complex code and public methods

2024-02-12 15:41 UTC, adudenamedruby approved these changes

2024-02-12 21:05 UTC, adudenamedruby commented
<img width="1114" alt="Screenshot 2024-02-12 at 4 03 53 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/11182210/34fb2c81-2340-41b2-aa4a-52cad7b81514">

2024-02-12 21:16 UTC, bendk commented
I think my lastest push should fix that.  `swiftlint` was passing for me locally at least after it.

2024-02-12 21:20 UTC, adudenamedruby commented
Hmm. Maybe I hit the wrong thing in BR. Lemme try again!

2024-02-12 22:44 UTC, adudenamedruby requested changes

2024-02-12 22:44 UTC, adudenamedruby commented on firefox-ios/Storage/Rust/RustFirefoxSuggest.swift
> +    public init(dataPath: String, cachePath, remoteSettingsConfig: RemoteSettingsConfig? = nil) throws {
You'll need to specifiy something here for the cache path. It can't just be an empty parameter.

2024-02-13 18:26 UTC, adudenamedruby commented
<img width="1077" alt="Screenshot 2024-02-13 at 1 26 10 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/11182210/db3e8c15-ed07-4b08-94f9-2a4def50a64b">

2024-02-13 18:49 UTC, bendk commented
I think I fixed the error, but I feel bad putting you through this feedback loop.  If it's too much, I can probably get someone from the suggest and/or sync team with a mac to make sure it compiles correctly.

2024-02-13 20:15 UTC, adudenamedruby commented
Looks like it built successfully but we got a weird git diff error:

<img width="1110" alt="Screenshot 2024-02-13 at 3 14 50 PM" src="https://github.com/mozilla-mobile/firefox-ios/assets/11182210/2cd9ef74-a6db-470b-a83a-c0705d97bd32">

2024-02-20 14:48 UTC, adudenamedruby commented
Just checking if there's any updates here?

2024-02-26 15:46 UTC, bendk commented
Sorry, just getting back from PTO.  I don't know what caused that git error, I don't see it locally.  I rebased to the current main and re-pushed, maybe that will fix it?

2024-03-01 21:55 UTC, bendk commented
I think all the errors should be fixed now.  @linabutler helped me get this one working.

2024-03-04 16:47 UTC, adudenamedruby commented
looks like tests are failing. :(

<img width="1491" alt="Screenshot 2024-03-04 at 11 47 00 AM" src="https://github.com/mozilla-mobile/firefox-ios/assets/11182210/4cb9d780-7837-4797-ae08-6c42c9192dc9">

2024-03-04 17:00 UTC, bendk commented
I think Lina mentioned that those tests were failing intermittently.  It's hard to see why this change would affect that.  I just rebased and re-pushed, maybe they'll work this time?

IIUC, some of that behavior is going to be changing soon as well (discussion in https://github.com/mozilla-mobile/firefox-ios/pull/18732).

2024-03-04 20:14 UTC, bendk commented
Looks like 1 of those tests is still failing.  I'm not sure what the next step should be here, I kind of want to say it's an intermittent failure, but I don't have enough knowledge to say one way or the other.

Sorry for the hassle with this one, what do you think should be the next step?

2024-03-05 16:56 UTC, bendk commented
Looks like it was my fault.  Lina says that my changes to `MockProfile` were breaking the tests and reverting them should fix it.

Just pushed a new commit that does that, let's hope it works.

2024-03-06 17:11 UTC, merged

2024-03-06 17:55 UTC, bendk commented
:champagne: