FXIOS-18911 | Remove Deferred usage from Authenticator
mozilla-mobile/firefox-ios pull request #19780
Opened 2024-04-13 12:59 UTC by imsanchit

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-18911)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/18911)

## :bulb: Description

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-04-17 23:03 UTC, dataports commented on firefox-ios/Client/Frontend/Browser/Authenticator.swift
>                  loginsHelper?.setCredentials(login)
Indentation can be moved up a level here

2024-04-17 23:20 UTC, dataports commented on firefox-ios/Client/Frontend/Browser/Authenticator.swift
> +                completionHandler(credentials)
Recommend adding a space below 153 just for a little bit more readability, it's a big block to parse when reading

2024-04-17 23:23 UTC, dataports requested changes
hi there @imsanchit thanks for your contribution! I just have a couple readability suggestions but it looks great otherwise. When those are done I can approve and merge.

2024-04-19 16:51 UTC, imsanchit commented
hi @dataports, have updated the PR as requested, please have a look.

2024-04-20 00:03 UTC, dataports approved these changes

2024-04-20 05:51 UTC, merged