Refactor MTE-2557 SettingsAppearanceTest and TestRail
mozilla-mobile/firefox-ios pull request #19946
Opened 2024-04-23 05:23 UTC by clarmso

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/MTE-2557)

## :bulb: Description
Ensure `SettingsAppearanceTests` have corresponding TestRail tests:
https://docs.google.com/document/d/1QDyaBvyJtxrLdyQIK4b3ZM9vHuuTiYnFDkH9ZqW2eWQ/edit

I have also uncommented some steps that are now working and applicable.

## :pencil: Checklist
You have to check all boxes before merging
- [X] Filled in the above information (tickets numbers and description of your work)
- [X] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-04-23 05:25 UTC, clarmso commented on focus-ios/focus-ios-tests/XCUITest/SettingAppearanceTest.swift
> +        let safariButton = app.collectionViews.buttons["Open in Default Browser"]
The order of menu item has been changed. I guess this step is to "Open in Default Browser". `5` is "Find in Page".

2024-04-23 05:26 UTC, clarmso commented on focus-ios/focus-ios-tests/XCUITest/SettingAppearanceTest.swift
> +        waitForExistence(app.staticTexts["Browsing history cleared"])
I can now relaunch Focus and clear history.

2024-04-23 07:44 UTC, isabelrios commented
As commented in the Jira ticket (https://mozilla-hub.atlassian.net/browse/MTE-2557) the settings tests are in different test rail test suites. And the automated tests are not only about settings Appearance because there are some related to Search Options. 
So I would rename this automated test suite as SettingsTest like the general Settings test suite in Test Rail.

I would also move the autocomple related tests in websiteAccessTest, like this one: https://github.com/mozilla-mobile/firefox-ios/blob/bf4b64d54ef7dbfb77d73e17a94b9f8f0efe3186/focus-ios/focus-ios-tests/XCUITest/WebsiteAccessTest.swift#L63 (and the other two) into this test suite because in Test Rail URL Autocomplete test suite is part of Settings.

2024-04-30 07:50 UTC, isabelrios commented on focus-ios/focus-ios-tests/XCUITest/SettingAppearanceTest.swift
> +    // Smoketest
Nit: We are missing the test rail link here...

2024-05-06 08:34 UTC, isabelrios requested changes
Please change the Test suite name and add the missing link

2024-05-07 05:38 UTC, clarmso commented on focus-ios/focus-ios-tests/FullFunctionalTests.xctestplan
> +        "SettingTest\/testVisitWebsite()",
TestRail says `testVisitWebsite()` should be a smoke test.

2024-05-07 05:41 UTC, clarmso commented on focus-ios/focus-ios-tests/SmokeTest.xctestplan
> +        "SettingTest\/testReEnableAutoComplete()",
I ensure that these `SettingTest`s are the full functional tests according to TestRail.

2024-05-07 07:51 UTC, isabelrios approved these changes

2024-05-07 07:52 UTC, merged