Bugfix FXIOS-7127 ⁃ Incorrect redirect to the latest visited YouTube video, after undoing close tab action
mozilla-mobile/firefox-ios pull request #20573
Opened 2024-06-06 11:05 UTC by dicarobinho

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7127)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/15837)

## :bulb: Description
When "Undo" a tab with a Youtube video, navigationAction.request return the Youtube Homepage URL instead the video URL, even if the tab have the correct URL.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-06-10 20:28 UTC, nbhasin2 requested changes

2024-06-10 20:28 UTC, nbhasin2 commented on firefox-ios/Client/Frontend/Browser/BrowserViewController/Extensions/BrowserViewController+WebViewDelegates.swift
> +            }
hmm this doesn't seem right, if a tab is being closed and user taps on undo then we usually have two options 
a) fully close the tab
b) partial close the tab

In both cases we should have the url to load and not worry about redirection request from youtube.
Also if the request is coming from a website itself then we shouldn't be the one handling it manually here.

Could you look into the actual undo logic and why the url that was previously there doesn't load?

2024-06-10 20:28 UTC, nbhasin2 commented on firefox-ios/Client/Frontend/Browser/BrowserViewController/Extensions/BrowserViewController+WebViewDelegates.swift
> +            }
DM me if you need any pointers

2024-06-11 14:37 UTC, dicarobinho commented
Closing for now this PR. After a sync with @nbhasin2, we should see how the Youtube security policies work in order to change this behaviour.

2024-06-11 14:37 UTC, closed without merging