Refactor FXIOS-21470 - Add Mutipath TCP (MPTCP) support
mozilla-mobile/firefox-ios pull request #21480
Opened 2024-08-07 09:05 UTC by Aperence

MPTCP is a TCP extension allowing to improve network reliabilty by using mutiple network interface for the same TCP connection. Check https://www.mptcp.dev and https://developer.apple.com/documentation/foundation/urlsessionconfiguration/improving_network_reliability_using_multipath_tcp for details. Changes to this repository includes introducing new configurations (defaultMPTCP/ephemeralMPTCP), replacing uses of default/ephemeral by these new configurations, introducing a sharedMPTCP property on URLSession and modifying the makeURL function to enable the handover mode by default

## :scroll: Tickets
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/21470)

## :bulb: Description

## :pencil: Checklist
You have to check all boxes before merging
- [X] Filled in the above information (tickets numbers and description of your work)
- [X] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [X] Wrote unit tests and/or ensured the tests suite is passing
- [X] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [X] If needed, I updated documentation / comments for complex code and public methods
- [X] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-08-07 18:00 UTC, mattreaganmozilla commented
Thanks for this PR @Aperence. Might be good to get some extra eyes on this (cc @nbhasin2).

2024-08-26 19:15 UTC, nbhasin2 commented on firefox-ios/Client/Extensions/URLSessionConfiguration+defaultMPTCP.swift
> +        // if we aren't building for iOS, defaultMPTCP == default, thus fall back to TCP
conf is ephemeral, not default
```suggestion
        // If we aren't building for iOS, ephemeralMPTCP == ephemeral, thus fallback to TCP
```

2024-08-26 19:15 UTC, nbhasin2 commented on firefox-ios/Client/Extensions/URLSessionConfiguration+defaultMPTCP.swift
> +        var conf = Self.ephemeral
nit: capitalization
```suggestion
        var conf = self.ephemeral
```

2024-08-26 19:15 UTC, nbhasin2 commented on firefox-ios/Client/Extensions/URLSessionConfiguration+defaultMPTCP.swift
> +        var conf = Self.default
nit: capitalization
```suggestion
        var conf = self.default
```

2024-08-26 19:16 UTC, nbhasin2 approved these changes
Approving with minor nits

2024-08-27 15:46 UTC, nbhasin2 commented
<img width="1672" alt="image" src="https://github.com/user-attachments/assets/392af800-9666-47ae-809b-f58f20071a5b">

@Aperence I see the following tests failing, would you mind looking into it and let us know if any support is required

2024-08-27 18:31 UTC, nbhasin2 commented on firefox-ios/Client/Extensions/URLSession+sharedMPTCP.swift
Thanks @Aperence, somehow the warnings have increased. Let me re-run the build but I would suggest trying locally to check the warnings between main / your branch 

Just posting in this file to have a chain of comments

2024-08-28 07:08 UTC, Aperence commented on firefox-ios/Client/Extensions/URLSession+sharedMPTCP.swift
Hello @nbhasin2,

Thank you for the review first.
After having checked the code, it seems like it was simply 2 immutable variables that were declared with a `var` keyword, instead of `let`. This should be fixed normally.

Also, I've seen that I forgot to add the [`Multipath`](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multipath) entitlement, I've just added it now (if it is fine ?).

Have a nice day

2024-09-03 20:45 UTC, nbhasin2 commented on firefox-ios/Client/Extensions/URLSession+sharedMPTCP.swift
Ah sorry, totally missed this. Let me double check to see if this is valid.

@Aperence did you try it locally or simply added it where it needs to get added?

Thanks again

2024-09-03 21:05 UTC, Aperence commented on firefox-ios/Client/Extensions/URLSession+sharedMPTCP.swift
I built locally the application to make sure that it doesn’t generate new warnings.

Thanks again for the follow-up !

2024-09-06 16:06 UTC, Aperence commented
Rebased it normally !

2024-09-21 07:39 UTC, Aperence commented
Any news about this ?

2024-09-24 19:33 UTC, OrlaM requested changes
I'm surprised this isn't just default URLSession behaviour and it's very strange that Apple require an entitlement for it 🤔 
Great change either way, one minor nit otherwise LGTM

2024-09-24 19:33 UTC, OrlaM commented on firefox-ios/Client/Extensions/URLSessionConfiguration+defaultMPTCP.swift
> +        #if os(iOS)
This version of Firefox is only built for iOS and there are no plans to built for any other OS in the ecosystem so you can remove this macro.

2024-09-25 14:11 UTC, Aperence commented
Just applied the requested change. It probably isn't enabled by default because some time ago, some other options weren't (well) supported with MPTCP, and they probably never reconsidered up to now to enable it by default.

2024-09-27 01:51 UTC, nbhasin2 commented
Running BR and if all looks well I can merge it in 🤞🏼

2024-09-27 01:51 UTC, nbhasin2 approved these changes

2024-09-27 12:59 UTC, OrlaM approved these changes

2024-09-27 18:58 UTC, nbhasin2 commented
@Aperence might wanna rebase this one last time as you have approvals but there are certain number of warnings that are more on this PR compared to main. 

Thanks and once green I can hit merge

2024-09-30 06:05 UTC, Aperence commented
Just rebased it now

2024-10-01 17:11 UTC, merged