Add FXIOS-9128 #20236 ⁃ Create accounts header for top of menu
mozilla-mobile/firefox-ios pull request #22147
Opened 2024-09-23 13:32 UTC by dicarobinho

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9128)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/20236)

## :bulb: Description
Moved the HeaderView to the ComponentLibrary in order to be reused. (for Menu and Tracking Protection)
Added some custom settings for header icon

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-09-23 13:33 UTC, dicarobinho commented
![Simulator Screenshot - iPhone 15 Pro - 2024-09-23 at 15 39 59](https://github.com/user-attachments/assets/289ac26a-f958-4525-9496-4233804695b2)

2024-09-23 17:07 UTC, cyndichin commented
FYI - added the component to be part of this ticket as well 
https://mozilla-hub.atlassian.net/browse/FXIOS-10083

2024-09-24 13:36 UTC, adudenamedruby requested changes

2024-09-24 13:36 UTC, adudenamedruby commented on BrowserKit/Sources/ComponentLibrary/Headers/HeaderView.swift
> +public final class HeaderView: UIView, ThemeApplicable {
This is.... uh... not descriptive enough. Perhaps `AccountHeaderView`?

2024-09-24 13:49 UTC, adudenamedruby approved these changes

2024-09-25 08:13 UTC, merged