Refactor FXIOS-7301 - Remove 2 closure_body_length violation from ContentBlockerSettingViewController.swift
mozilla-mobile/firefox-ios pull request #22277
Opened 2024-09-30 22:18 UTC by ionixjunior

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7301)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16442)

## :bulb: Description

This PR removes 2 `closure_body_length` violations from the `ContentBlockerSettingViewController.swift` file. It extracts the telemetry logic to a new function.

I’ve noticed a potential bug with the `self.linkButton.isHidden = true` logic when selecting the "strict" option. This line should hide the "Learn more" button in the footer of the first section, but it doesn’t seem to work. I’ve observed the same behavior on the main branch as well. Could someone confirm if this is indeed a bug?

Below is a screenshot of the button that should be hidden when strict mode is selected.

![Screenshot 2024-09-30 at 19 10 04](https://github.com/user-attachments/assets/c4c79cb1-9c33-4529-b31d-9b6dd11e356c)

This PR is part of a series of PRs described here https://github.com/mozilla-mobile/firefox-ios/issues/16442#issuecomment-2197676804.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-10-01 06:18 UTC, FilippoZazzeroni approved these changes
Thank you for the contribution, great work 🎉 🎉

2024-10-01 06:35 UTC, FilippoZazzeroni commented
@ionixjunior i had a look to the link button not hiding properly. basically the tableView reload always restore its visibility after the onChecked block completes.
To address this you can just remove it from the table view the isHidden setting and leaving it fully in the onChecked and also remember to set the initial value while instantiating the view controller.

2024-10-01 06:36 UTC, FilippoZazzeroni requested changes
Setting the PR as needed changes so we can address also the link button bug! Thanks really for noticing it.

2024-10-01 22:18 UTC, ionixjunior commented
@FilippoZazzeroni done! I've made a basic implementation followed by a small refactors. The last three commits might not be necessary - let me know what you think.

Below is a video demonstrating the fix.

https://github.com/user-attachments/assets/6b88e4f4-1c9a-418a-9439-57cccce4e8f7

2024-10-03 06:57 UTC, FilippoZazzeroni approved these changes
Just a nit, i would not use on line method they impact IMO in the readability, i think here since we have to use it in just two place we can just put the one line in the appropriate spots in the methods.
Thanks again for the contributions 🎉 🎉 . Btw if you'd like more challenging tasks or different topic just let me know i'll update the list of issues or assign a custom one to you.

2024-10-04 00:48 UTC, ionixjunior commented
@FilippoZazzeroni yeah, that makes sense. I wanted to centralize the logic to ensure consistency in both places, but I agree that sometimes following clean code principles can make code navigation harder.

Sure! Thank you! I'm currently committed to finishing the issue regarding the `closure_body_length`, and it's been very interesting. Everyone here has been incredibly helpful, and the project is very well-organized. I'm really enjoying contributing, and once I wrap up this task, I'll reach out to you about taking on something new.

Branch updated and rebased.

2024-10-04 07:40 UTC, FilippoZazzeroni commented
@ionixjunior I'm really happy to hear that, thank you very much 🎉 . Yes whenever just hit me up and i'll find something else

2024-10-08 08:26 UTC, merged