Refactor FXIOS-7301 - Remove 1 closure_body_length violation from NavigationBarState.swift
mozilla-mobile/firefox-ios pull request #22679
Opened 2024-10-21 22:04 UTC by ionixjunior

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-7301)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/16442)

## :bulb: Description

This PR removes 1 `closure_body_length` violation from the `NavigationBarState.swift` file by extracting the switch case statements to new methods.

This PR is part of a series of PRs described here https://github.com/mozilla-mobile/firefox-ios/issues/16442#issuecomment-2197676804.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-10-29 19:02 UTC, FilippoZazzeroni requested changes
Nit i would just restore the default state. The rest looks great thank you very much for contributing 🎉

2024-10-29 21:41 UTC, ionixjunior commented on firefox-ios/Client/Frontend/Browser/Toolbars/Redux/NavigationBarState.swift
> +            return state
Fixed and rebased.

2024-10-30 13:24 UTC, FilippoZazzeroni commented on firefox-ios/Client/Frontend/Browser/Toolbars/Redux/NavigationBarState.swift
> +            return state
Perfect thank you @ionixjunior it looks good 🎉

2024-10-30 13:24 UTC, FilippoZazzeroni approved these changes

2024-10-30 18:26 UTC, thatswinnie approved these changes

2024-10-31 13:37 UTC, merged