Add FXIOS-9885 - Add last hour section to history tab
mozilla-mobile/firefox-ios pull request #22768
Opened 2024-10-25 19:56 UTC by DanielDervishi

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9885)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/21682)

## :bulb: Description

The `DateGroupedTableData` struct was coupled to specific timestamps. I augmented it to be able to operate with any set of timestamps passed to it. I know that there were other places in which the struct was used and so I wasn't confident in augmenting the structure to just include last hour in every case.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-10-25 20:14 UTC, adudenamedruby requested changes

2024-10-25 20:14 UTC, adudenamedruby commented on firefox-ios/Client/Frontend/Strings.swift
> +                comment: "This label is meant to signify the section containing a group of items from the past hour")
Check out the wiki on how to add stringns. This doesn't seem to align with that. We'll need version identifiers, a tablename, and a better comment for translators that don't have context for this.

2024-10-25 20:14 UTC, adudenamedruby commented on firefox-ios/Shared/DateGroupedTableData.swift
> +    var timestamps: [TimeInterval] = []
The changes in this file feel like they all easily tested and we should have tests for them to know things are operating exactly as we're expecting. :)

2024-10-28 19:48 UTC, adudenamedruby approved these changes
🔥

2024-10-29 10:43 UTC, isabelrios commented
There is a UI test failing consistently for this PR, I think there may be changes in the History panel causing this. The failing test is:
`testClearRecentHistory` with failure: `/Users/vagrant/git/firefox-ios/firefox-ios-tests/Tests/XCUITests/BaseTestCase.swift:158 - failed - Timed out waiting for element "Older" StaticText to exist in 20.0 seconds`

Let us know if you need help fixing / updating it cc @mdotb-moz @clarmso

2024-10-29 15:49 UTC, clarmso commented on firefox-ios/firefox-ios-tests/Tests/XCUITests/HistoryTests.swift
> +        mozWaitForElementToExist(app.staticTexts["Last month"])
The label is now "Last month".
![Simulator Screenshot - iPhone 15 Pro - 2024-10-29 at 10 26 45](https://github.com/user-attachments/assets/d4c1837a-35df-4ac3-b458-eb19ef83ce25)

2024-11-05 14:38 UTC, isabelrios approved these changes

2024-11-05 14:39 UTC, merged

2024-11-06 19:10 UTC, DanielDervishi commented
@Mergifyio backport release/v133