Add FXIOS-9770 Change Default Folder Name from Mobile Bookmarks to Bookmarks (part 1)
mozilla-mobile/firefox-ios pull request #22972
Opened 2024-11-07 12:23 UTC by dataports

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-9770)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/21445)

## :bulb: Description
This is part of the Bookmarks feature work. This ticket has multiple parts I'm splitting them up into separate pull requests to keep them small.
This is the first part of this ticket which simply adds the string for the Bookmarks title, renames the old code to use Legacy naming, and shows the correct title depending whether the new Bookmarks feature is enabled or not.

## Old Appearance (Legacy)
<img src="https://github.com/user-attachments/assets/45e018a7-295c-4b3f-bef7-08095492ad5f" width=40% height=40%>
<img src="https://github.com/user-attachments/assets/71dca9bc-69bb-425f-a32b-892bed87e257" width=40% height=40%>

## New Appearance (Feature Flag enabled from debug menu)
<img src="https://github.com/user-attachments/assets/eea92bf9-6111-4d3e-b320-21887437ce81" width=40% height=40%>
<img src="https://github.com/user-attachments/assets/619ea0c7-efa4-4bae-92fd-5ed8b658917a" width=40% height=40%>

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-11-07 22:24 UTC, MattLichtenstein requested changes
When testing with the feature flag enabled, I'm still seeing the "Mobile Bookmarks" string on the edit bookmark view, after saving a bookmark, and selecting the edit button on the toast

https://github.com/user-attachments/assets/729203f1-ea9c-498e-bf04-57a239ad28a0

2024-11-08 18:33 UTC, MattLichtenstein approved these changes

2024-11-10 19:00 UTC, dataports commented
> When testing with the feature flag enabled, I'm still seeing the "Mobile Bookmarks" string on the edit bookmark view, after saving a bookmark, and selecting the edit button on the toast
> Simulator.Screen.Recording.-.iPhone.15.-.2024-11-07.at.17.24.31.mp4

Looks like we missed an entry point into the Bookmarks panel with the feature flag. I will push a fix for this shortly.

2024-11-10 20:32 UTC, dataports commented
@MattLichtenstein actually just kidding, I'm going to merge this, I made a [follow up ticket here](https://mozilla-hub.atlassian.net/browse/FXIOS-10496)

2024-11-10 20:32 UTC, merged