Refactor FXIOS-10492 UITests > Fix skipped flakey tests
mozilla-mobile/firefox-ios pull request #22987
Opened 2024-11-08 00:57 UTC by hemche

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-10492)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/22986)

## :bulb: Description

This issue is regarding these two skipped/disabled tests
- [testPrivateTab()](https://github.com/mozilla-mobile/firefox-ios/blob/main/firefox-ios/firefox-ios-tests/Tests/XCUITests/JumpBackInTests.swift#L54)
it's failing because `twitter.com` is now `x.com`
**Resolution:** Updated the website to wikipedia

- [testPopUpBlocker()](https://github.com/mozilla-mobile/firefox-ios/blob/main/firefox-ios/firefox-ios-tests/Tests/XCUITests/NavigationTest.swift#L342C10-L342C26)
It is failing because the `openUrl` function is not clearing the existing text in the url bar and appending the new url to existing url.
**Resolution:** Added a `clearAndTypeText` function which will clear any existing text in the url bar and then type the url

Tested both these tests locally on iPhone and iPad simulators ✅ 
## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-11-08 09:58 UTC, isabelrios commented on firefox-ios/firefox-ios-tests/Tests/XCUITests/FxScreenGraph.swift
> -            app.textFields.firstMatch.typeText(url)
This change will afffect all the tests that interact with the UrlBar.. some test type and need the field to be clear, but some others type and add text in different scenarios. I don't think we can do this change.
There is one test part of the smoketest failing in this PR and I think is related. There will be more that may fail as part of the Full Functional.
Please revert this change or create that method in the BaseTestCase to be used specifically for tests that could benefit from this, not affecting all tests and how they interact with this element.
Thanks!

2024-11-08 09:58 UTC, isabelrios requested changes
As per comment

2024-11-11 09:31 UTC, mdotb-moz approved these changes
LGTM

2024-11-11 09:40 UTC, isabelrios commented
@mdotb-moz @dragosb01 once this land, could you please change the status of the tests in TestRail? thank you!

2024-11-12 15:51 UTC, mdotb-moz requested changes
@hemche Can you please be sure the tests are passing? 

Is failing for me locally

![Screenshot 2024-11-12 at 16 49 54](https://github.com/user-attachments/assets/1c3076cf-51d2-48a5-aaab-041a0a467f1d)

It fails on the line 133: 

![Screenshot 2024-11-12 at 16 52 32](https://github.com/user-attachments/assets/0a2b811d-72cd-47c6-a018-0e3a8909ce91)

The failure is "**Failed to tap "crossLarge" Button: No matches found for Elements matching predicate '"Amazon.com. Spend less. Smile more." IN identifiers' from input {(**"

2024-11-12 16:39 UTC, hemche commented
> @hemche Can you please be sure the tests are passing?
> 
> Is failing for me locally
> 
> ![Screenshot 2024-11-12 at 16 49 54](https://private-user-images.githubusercontent.com/177202774/385356189-1c3076cf-51d2-48a5-aaab-041a0a467f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0Mjk1MTksIm5iZiI6MTczMTQyOTIxOSwicGF0aCI6Ii8xNzcyMDI3NzQvMzg1MzU2MTg5LTFjMzA3NmNmLTUxZDItNDhhNS1hYWFiLTA0MWEwYTQ2N2YxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxNjMzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2ZjMjFiM2I5ZWUwZTYwOGU2NmJiNzBlNWE1ODJmYjgzZWI1MWY1MDA0NGNkNWE2NTkzNmUzMDQyODFhMGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K0mCuhjgOdKI5awwe4sa3_MGP8b3JW0QXRy9ATTRzRg)
> 
> It fails on the line 133:
> 
> ![Screenshot 2024-11-12 at 16 52 32](https://private-user-images.githubusercontent.com/177202774/385357386-0a2b811d-72cd-47c6-a018-0e3a8909ce91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0Mjk1MTksIm5iZiI6MTczMTQyOTIxOSwicGF0aCI6Ii8xNzcyMDI3NzQvMzg1MzU3Mzg2LTBhMmI4MTFkLTcyY2QtNDdjNi1hMDE4LTBlM2E4OTA5Y2U5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxNjMzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDc1MWFiYjkzNzVjZTE2ZmQ3ODZhNTE1N2ZlODU2NzlhYzQ1MmYxNmFlNDA4NDg2NDFjZGM3NTY5YjUwOGUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mdYwjDKACX6kQgo9FDbEvtgSxIZ9n6wjeoD5Z0q821M)
> 
> The failure is "**Failed to tap "crossLarge" Button: No matches found for Elements matching predicate '"Amazon.com. Spend less. Smile more." IN identifiers' from input {(**"
> 
> Maybe we can use local test sites instead amazon, google, etc.

There was a difference in how the www.amazon.com tile is being displayed in your screenshot and my local one. Test passed multiple times in my local. However i changed it to `www.mozilla.org` instead of `www.amazon.com` and it passed again repeatedly 10 times in my local. Please run on your end and let me know if this fixes the issue.

If you still think the local webpages might be a good idea, let me know, which local webpage can i use for this testing. Can i use something like `http://localhost:\(serverPort)/test-fixture/test-example.html` ?

2024-11-12 18:29 UTC, mdotb-moz approved these changes
LGTM

2024-11-12 18:57 UTC, mdotb-moz commented
@hemche It looks like the test failed in the smoke test 3 in bitrise

2024-11-12 19:49 UTC, hemche commented
@mdotb-moz Added localhost url as a last resort as it looks like there is a different behaviour while accessing from the mozilla systems. Fixed in [f6bf1ae](https://github.com/mozilla-mobile/firefox-ios/pull/22987/commits/f6bf1aee331dd011fa5410f73ac010a31a8a6f0b) 🤞🏽

2024-11-12 22:19 UTC, merged

2024-11-12 22:20 UTC, mdotb-moz commented
Thank you @hemche for your support. I merged the PR