Add OMC-1016 [Nimbus] "Open Share Sheet" Card Messaging Action
mozilla-mobile/firefox-ios pull request #23094
Opened 2024-11-13 15:39 UTC by halemu

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/OMC-1016)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/22967)

## :bulb: Description
Adds a new messaging action to open the share sheet from a message. The message is configurable using Nimbus and contains a url and title field.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-11-13 15:43 UTC, halemu commented
This is a work in progress, looking for feedback to ensure I'm heading in the right direction! 🙏 
I'm not able to test it fully since that requires a developer account setup, I'd appreciate testing this using an iPhone as well, thanks!

2024-11-13 20:25 UTC, adudenamedruby commented
@halemu I changed this to draft until it's ready, just so it's less confusing for review priorities. :)
Feel free to mark as `Ready for Review` whenever you're done.

2024-11-15 14:40 UTC, adudenamedruby commented
As a first quick pass, this is gonna fail on swfitlint due to indentation, so you can either do a swiftlint pass on it, or just do a `re-indent` in the files that you changed.

2024-11-15 16:24 UTC, halemu commented
Thanks, updated 👍

2024-11-15 16:31 UTC, adudenamedruby requested changes

2024-11-15 16:31 UTC, adudenamedruby commented on firefox-ios/Client/Coordinators/Router/Route.swift
> +    case sharesheet(url: URL, title: String?)
we should add documentation for this, like the rest of the functions defined here.

2024-11-15 16:31 UTC, adudenamedruby commented on firefox-ios/Client/Coordinators/Router/RouteBuilder.swift
> +                // Convert the linkString (String?) to a URL? using URL(string:)
nit: not really needed, as the code is pretty self documenting here

2024-11-15 19:32 UTC, adudenamedruby approved these changes

2024-11-15 21:06 UTC, halemu commented
Would appreciate if someone can merge this in since I don't have write access yet, thanks!

2024-11-15 21:07 UTC, merged

2024-11-18 17:31 UTC, halemu commented
@Mergifyio backport release/v133

Requesting backport to support iOS Sharesheet experiment.

2024-11-18 17:49 UTC, adudenamedruby commented
I've reached out for details.

2024-11-18 18:02 UTC, adudenamedruby commented
@Mergifyio backport release/v133