Bugfix FXIOS-10382 [Focus] Fixed the 'studies' toggle function
mozilla-mobile/firefox-ios pull request #23724
Opened 2024-12-12 15:27 UTC by Umair-ios

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-10382)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/22752)

## :bulb: Description
To sync 'studies' toggle with 'Send data usage', Added extra check before turning 'studies' toggle on, 

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [ ] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [x] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-12-16 23:31 UTC, MattLichtenstein requested changes
Looks good, just a little spacing cleanup.

2024-12-17 13:27 UTC, Umair-ios commented on focus-ios/Blockzilla/Settings/Controller/SettingsViewController.swift
> +
Removed in [edd23ad](https://github.com/mozilla-mobile/firefox-ios/pull/23724/commits/edd23adefe3c2c83fca30ed05bccfa8e10e78928)

2024-12-17 13:27 UTC, Umair-ios commented on focus-ios/Blockzilla/Settings/Controller/SettingsViewController.swift
> +
Removed in [edd23ad](https://github.com/mozilla-mobile/firefox-ios/pull/23724/commits/edd23adefe3c2c83fca30ed05bccfa8e10e78928)

2024-12-17 14:49 UTC, MattLichtenstein approved these changes
Awesome, thank you @Umair-ios for the contribution 🎉

2024-12-17 14:49 UTC, merged