Refactor FXIOS-10205 - Resolve 6 implicitly_unwrapped_optional violations in LegacyFeatureFlagsManager
mozilla-mobile/firefox-ios pull request #23804
Opened 2024-12-17 14:20 UTC by tonell-m

## :scroll: Tickets
[Jira ticket](https://mozilla-hub.atlassian.net/browse/FXIOS-10205)
[Github issue](https://github.com/mozilla-mobile/firefox-ios/issues/22337)

## :bulb: Description

Continuing resolving `implicitly_unwrapped_optional` violations in order to enable the rule for further developments.

## :pencil: Checklist
You have to check all boxes before merging
- [x] Filled in the above information (tickets numbers and description of your work)
- [x] Updated the PR name to follow our [PR naming guidelines](https://github.com/mozilla-mobile/firefox-ios/wiki/Pull-Request-Naming-Guide)
- [x] Wrote unit tests and/or ensured the tests suite is passing
- [ ] When working on UI, I checked and implemented accessibility (minimum Dynamic Text and VoiceOver)
- [ ] If needed, I updated documentation / comments for complex code and public methods
- [ ] If needed, added a backport comment (example `@Mergifyio backport release/v120`)

2024-12-17 15:53 UTC, MattLichtenstein requested changes
Small spacing changes, but otherwise looks good!

2024-12-17 15:53 UTC, MattLichtenstein commented on firefox-ios/Client/FeatureFlags/LegacyFeatureFlagsManager.swift
> +        }
```suggestion
        guard let profile else { return false }
```

2024-12-17 15:53 UTC, MattLichtenstein commented on firefox-ios/Client/FeatureFlags/LegacyFeatureFlagsManager.swift
> +        }
```suggestion
        guard let profile else { return nil }
```

2024-12-17 15:53 UTC, MattLichtenstein commented on firefox-ios/Client/FeatureFlags/LegacyFeatureFlagsManager.swift
> +        }
```suggestion
        guard let profile else { return }
```

2024-12-17 15:53 UTC, MattLichtenstein commented on firefox-ios/Client/FeatureFlags/LegacyFeatureFlagsManager.swift
> +        }
```suggestion
        guard let profile else { return }
```

2024-12-18 08:10 UTC, tonell-m commented
@MattLichtenstein Done! Thanks for the review

2024-12-18 17:13 UTC, MattLichtenstein approved these changes

2024-12-18 17:14 UTC, merged