Widget telemetry
mozilla-mobile/firefox-ios pull request #7258
Opened 2020-09-02 17:20 UTC by sblatz

*Thank you for submitting a pull request, your contributions are greatly appreciated!*

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Please make sure you've run the test scheme and all the tests pass. If your changes affect existing tests please make sure to update the tests as well.

2020-09-02 20:48 UTC, sblatz commented
@liuche for data review.

# Request for data collection review form 
1. What questions will you answer with this data?
* Which widgets do users use most frequently?

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
* Provide information essential for advancing a business objective such as supporting OKRs.
* Help us prioritize feature work / bug fixes on widgets

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
* No other way to collect this data.

4. Can current instrumentation answer these questions?
* No, widgets were just added and we have no existing telemetry for them.

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.

Measurement Description | Data Collection Category | Tracking Bug # |
| --- | ----- | ----- |
When the quick sites "search" widget is opened | 2 | https://github.com/mozilla-mobile/firefox-ios/issues/7097
When the quick sites "open link" widget is opened | 2 | https://github.com/mozilla-mobile/firefox-ios/issues/7097
When the quick sites "close private tabs" widget is opened | 2 | https://github.com/mozilla-mobile/firefox-ios/issues/7097
When the quick sites "search privately" widget is opened | 2 | https://github.com/mozilla-mobile/firefox-ios/issues/7097
When the quick sites "open tabs" widget is opened | 2 | https://github.com/mozilla-mobile/firefox-ios/issues/7097
When the quick sites "top sites" widget is opened | 2 | https://github.com/mozilla-mobile/firefox-ios/issues/7097

6. How long will this data be collected? Choose one of the following:
* I want this data to be collected for 6 months initially (potentially renewable).

7. What populations will you measure?
All countries, locales, and channels that have data collection on.

8. If this data collection is default on, what is the opt-out mechanism for users?
Toggle switch for 'Send Usage Data' in the app settings.

9. Please provide a general description of how you will analyze this data.
By monitoring the count of how often users are performing these actions.

10. Where do you intend to share the results of your analysis?
With the mobile team.

11. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:
No.

2020-09-02 23:51 UTC, liuche requested changes
I don't see any metrics.yaml changes, so does this change not use Glean for telemetry?

One thing that I'll need before doing data review is public documentation for this (such as what metrics.yaml does - maybe iOS has a separate non-glean telemetry doc that you could add to, if this isn't going to use Glean?)

2020-09-08 15:14 UTC, AaronMT commented
This is needed to build on Xcode 12b6 on ```main```

2020-09-10 19:53 UTC, garvankeeley requested changes

2020-09-10 19:53 UTC, garvankeeley commented on WidgetKit/Helpers.swift
> +    var events = prefs.arrayForKey(prefKeySyncEvents) as? [Data] ?? []
`if events.count > 20 { log to sentry that we are piling up too many events and return url }`

2020-09-10 19:53 UTC, garvankeeley commented on Client/Application/AppDelegate.swift
> +
missing on this line: clearing the array

2021-01-08 20:07 UTC, closed without merging