FXIOS 977 link sharing via whatsapp not working
mozilla-mobile/firefox-ios pull request #7505
Opened 2020-10-16 08:33 UTC by kathishivaramreddy

Issue Fixed :-
https://github.com/mozilla-mobile/firefox-ios/issues/7414

Why Issue was happening:-

The reason links were not getting shared via whatsapp was 
**webView(_:createWebViewWith:for:windowFeatures:)** was returning nil.

How is it fixed:-
1.url scheme is checked for whatsapp before returning nil
2.url is checked with canOpenUrl to see if app is installed on phone or not.
3.whatsapp scheme is added to LSApplicationQueriesSchemes

Tested on:-
Iphone 7
iOS 13.6.1

2020-10-16 08:34 UTC, kathishivaramreddy commented
@isabelrios @dnarcese Please take a look.I have provided detailed explanation in PR title.
Thanks

2020-10-16 11:58 UTC, isabelrios commented on UITests/SecurityTests.swift
> -    func testDataURL() {
This was removed in a previous commit, I guess you need to rebase main to have latest changes correctly

2020-10-16 12:00 UTC, isabelrios commented
Apart from the comment I left this LGTM (tests and build wise)

2020-10-16 13:36 UTC, kathishivaramreddy commented
@isabelrios Made changes according to last comment, have rebased the main branch.Ready For Re Review. Thanks!

2020-10-19 14:48 UTC, isabelrios commented
For me this PR looks good, but adding @dnarcese to take a deeper look to the fix since she may be more familiar than me with that code.

2020-10-19 14:49 UTC, isabelrios approved these changes

2020-10-20 02:14 UTC, kathishivaramreddy commented
@isabelrios @dnarcese  Can you add hacktoberfest-accepted label to this PR ?

2021-05-05 17:51 UTC, dnarcese requested changes

2021-05-05 17:51 UTC, dnarcese commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
> +            if url.scheme == "whatsapp" && UIApplication.shared.canOpenURL(url){
```suggestion
            if url.scheme == "whatsapp" && UIApplication.shared.canOpenURL(url) {
```

2021-05-05 17:51 UTC, dnarcese commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WebViewDelegates.swift
> +
```suggestion

```

2021-05-05 17:52 UTC, dnarcese approved these changes

2021-05-05 20:47 UTC, merged