FXIOS-1456 fixes #7933 adds Save to Files to share sheet for PDF
mozilla-mobile/firefox-ios pull request #8014
Opened 2021-02-21 17:51 UTC by ageofadz

Fixes #7933 by adding Save to Files to share sheet if a PDF is shared. This is done by passing the URL directly in as activityItems in the activityViewController in ShareExtensionHelper.

![IMG_1933](https://user-images.githubusercontent.com/20655124/108633646-eee76780-743a-11eb-9d81-c97d4c859e68.jpg)

2021-03-15 09:33 UTC, bentsionmp commented
Any idea if it'll share all types of files? Like .Doc or just PDF when loaded?
Also when what version is expected to fix this in public release?

2021-03-15 09:35 UTC, wachabaha commented
[**_****_**](https://apps.apple.com/de/app/butter-royale/id1464623715)

2021-03-15 09:35 UTC, wachabaha approved these changes

2021-03-15 09:37 UTC, wachabaha commented
https://apps.apple.com/de/app/butter-royale/id1464623715

2021-03-16 19:01 UTC, ageofadz commented
> Any idea if it'll share all types of files Like .Doc or just PDF when loaded?
> Also when what version is expected to fix this in public release?

These changes work with .doc files - as for release schedule, I believe that is up to Mozilla

2021-05-18 13:22 UTC, electricRGB requested changes

2021-05-18 13:22 UTC, electricRGB commented on Client/Frontend/Share/ShareExtensionHelper.swift
> +        }
```suggestion
        var activityViewController: UIActivityViewController
        if isFile(url: url) {
            activityViewController = UIActivityViewController(activityItems: [url], applicationActivities: nil)
        } else {
            activityViewController = UIActivityViewController(activityItems: activityItems, applicationActivities: nil)
        }
```

2021-05-18 13:23 UTC, electricRGB approved these changes

2021-05-18 14:17 UTC, isabelrios commented
Please do not merget yet...Looking at this PR since build failed to build and run the tests, see logs in here: 
https://app.bitrise.io/build/5f973a7aab57056c#?tab=log

2021-05-18 15:18 UTC, electricRGB commented
@isabelrios I rebased their branch and rerunning BR to see if it works..

2021-05-18 16:21 UTC, electricRGB commented
@isabelrios BR failed again, but it's failing on `testPromptPassCodeUponReentry` which is not touched by this PR at all. Will wait for your approval before merging, but I think it's safe.

2021-05-19 11:45 UTC, isabelrios commented
> @isabelrios BR failed again, but it's failing on `testPromptPassCodeUponReentry` which is not touched by this PR at all. Will wait for your approval before merging, but I think it's safe.

yes, it is not related at all to this changes but I have seen it failing 3 out of 3 times, let me investigate it before merging please. If these changes are important to land, then please disable the tests. I will try to come back to this later today

2021-05-19 12:51 UTC, electricRGB commented
Yep. Will wait. These can go in at any point this week or so. :)

2021-05-19 15:43 UTC, isabelrios commented
I tried this locally and test is working, not sure what's happening on BR for that test and this PR, it is green for the rest. Feel free to land this and I will keep and eye on that. Thanks and sorry for the noise here :)

2021-05-19 16:24 UTC, electricRGB commented
No worries. Thanks so much Isabel! :)

2021-05-19 16:25 UTC, merged