Added License info in Readme.md
mozilla-mobile/firefox-ios pull request #8097
Opened 2021-03-09 09:20 UTC by gokulnair2001

#8096 
## Readme Updation
* So this is a small contribution which is really important in such repositories. Because before contributing to any repository the contributor must know the License policy. 
* Without the proper knowledge policy there are chances that the user exploit the project.
* So to stop such activities we must add the ```License```  info in the Readme.md file such that the user remembers to have a look on it.
* This enhancement is quite small but really important when we see future aspects of such amazing application.

2021-03-10 06:20 UTC, giginet commented
oops, I approved the wrong repository.... 🙏

2021-03-10 06:23 UTC, gokulnair2001 commented
@giginet its ok, but this one was also meant to be approved, since this one is too a valid change.
Have a look on this too :).

2021-03-10 06:43 UTC, gokulnair2001 commented
Hi kohki, actually I saw the same problem which was in Puree in the Firefox
repo, if possible do merge this PR too :).

On Wed, Mar 10, 2021 at 11:50 AM Kohki Miki <notifications@github.com>
wrote:

> oops, I approved the wrong repository.... 🙏
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla-mobile/firefox-ios/pull/8097#issuecomment-794951234>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANNFOY2CABCP566MJ5A4RZ3TC4FSBANCNFSM4Y3EPY6A>
> .
>

2021-03-10 13:01 UTC, gokulnair2001 commented
Hi Kohki, sorry to spam you, but if you notice my PR in Firefox iOS (PR
#8097), you can see that the PR is a valid PR, so if possible you can
approve it with a positive comment, like right now you wrote its *done by
mistake*, so if possible do review the code and approve it with a positive
comment.

It will be a great help if you approve my PR.

Yours sincerely
Gokul R Nair

On Wed, Mar 10, 2021 at 12:13 PM Gokul Nair <gokulnair.2001@gmail.com>
wrote:

> Hi kohki, actually I saw the same problem which was in Puree in the
> Firefox repo, if possible do merge this PR too :).
>
> On Wed, Mar 10, 2021 at 11:50 AM Kohki Miki <notifications@github.com>
> wrote:
>
>> oops, I approved the wrong repository.... 🙏
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/mozilla-mobile/firefox-ios/pull/8097#issuecomment-794951234>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ANNFOY2CABCP566MJ5A4RZ3TC4FSBANCNFSM4Y3EPY6A>
>> .
>>
>

2021-03-10 21:04 UTC, boek requested changes
Thanks for the contribution! Let's try to stay consistent with our other repositories. If you want to replicate the style and position of [Android Components](https://github.com/mozilla-mobile/android-components/blob/master/README.md#license) that would be great 👍

2021-03-11 02:29 UTC, gokulnair2001 commented
> Thanks for the contribution! Let's try to stay consistent with our other repositories. If you want to replicate the style and position of [Android Components](https://github.com/mozilla-mobile/android-components/blob/master/README.md#license) that would be great 👍

ya sure, will make the changes accordingly and push a new PR.

2021-03-11 02:41 UTC, gokulnair2001 commented
> Thanks for the contribution! Let's try to stay consistent with our other repositories. If you want to replicate the style and position of [Android Components](https://github.com/mozilla-mobile/android-components/blob/master/README.md#license) that would be great 👍
@boek 
Do have a look I had made the changes as required :)

2021-03-25 16:47 UTC, boek approved these changes

2021-03-25 16:47 UTC, merged