Update release checklist origanization & links
mozilla-mobile/firefox-ios pull request #8811
Opened 2021-07-08 14:42 UTC by electricRGB

2021-07-08 14:58 UTC, dnarcese requested changes

2021-07-08 14:58 UTC, dnarcese commented on .github/ISSUE_TEMPLATE/release_checklist_template.md
> +### Branch setup, steps typically done when creating new version branch:
```suggestion
```
Probably don't need this

2021-07-08 14:58 UTC, dnarcese commented on .github/ISSUE_TEMPLATE/release_checklist_template.md
> +These items should be completed as soon as possible, preferrably on soft code freeze day. Due to timing issues, they may not be available until hard code freeze, and must
Incomplete sentence

2021-07-08 14:58 UTC, dnarcese commented on .github/ISSUE_TEMPLATE/release_checklist_template.md
>  - [ ] Release Notes updated
Let's make this ordering
- rel notes
- screenshots and locales
- submit
- rollout

2021-07-08 14:58 UTC, dnarcese requested changes

2021-07-08 14:58 UTC, dnarcese commented on .github/ISSUE_TEMPLATE/release_checklist_template.md
> +## Hard Code Freeze
```suggestion
## Hard Freeze Items
```
Just for consistency

2021-07-09 15:28 UTC, electricRGB commented
@dnarcese comments have been addressed. :) Also.... I have no idea why I left that sentence incomplete. lol

2021-07-09 15:30 UTC, dnarcese approved these changes

2021-07-10 08:13 UTC, andikaleonardo approved these changes

2021-07-12 13:06 UTC, merged