Attempt to fix BR tests and fix warnings
mozilla-mobile/firefox-ios pull request #9885
Opened 2022-01-28 15:44 UTC by lmarceau

- Clean up left over from Carthage with Adjust SDK (It's added throught SPM not Carthage)
- Add information on testBlankPopupURL() to try to figure out why it fails on BR
- Try a fix with a completion to ensure testPrivateTabsAreArchived() passes on BR
- Fix minor warnings

2022-01-28 16:01 UTC, nbhasin2 commented
Carthage cleanup happened as a part of spm brach.

2022-01-28 16:06 UTC, nbhasin2 requested changes
Let's try to keep the pr in terms of fixing tests and not make any changes to pbxproj as I did the same change in spm branch. This way we can avoid merge conflicts.

2022-01-28 19:41 UTC, nbhasin2 approved these changes

2022-01-31 08:58 UTC, isabelrios commented
FYi, There is still one unit test failing: https://addons-testing.bitrise.io/builds/f0e4fdd0-2c96-446e-9287-2e9e53ed6472/summary?status=failed

![Captura de pantalla 2022-01-31 a las 9 57 09](https://user-images.githubusercontent.com/1897507/151765048-9ab44181-881b-4d19-b183-666836782af7.png)

2022-01-31 21:37 UTC, merged